package com.caasa.comexsap.exportaciones.model.domain;

import java.math.BigDecimal;
import java.util.Date;

public class ComexstPackinglistAereo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEN_ID
     *
     * @mbg.generated
     */
    private Integer plaenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEN_ID_EXPORTACION
     *
     * @mbg.generated
     */
    private Integer plaenIdExportacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEN_NUMERO
     *
     * @mbg.generated
     */
    private Integer plaenNumero;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEV_CODIGO
     *
     * @mbg.generated
     */
    private String plaevCodigo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEV_MATERIAL
     *
     * @mbg.generated
     */
    private String plaevMaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEN_CANTIDAD
     *
     * @mbg.generated
     */
    private Integer plaenCantidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEN_PESO_BRUTO
     *
     * @mbg.generated
     */
    private BigDecimal plaenPesoBruto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEV_DIMENSION
     *
     * @mbg.generated
     */
    private String plaevDimension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEV_USUARIO_CREACION
     *
     * @mbg.generated
     */
    private String plaevUsuarioCreacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAED_FECHA_CREACION
     *
     * @mbg.generated
     */
    private Date plaedFechaCreacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEV_USUARIO_MODIFICACION
     *
     * @mbg.generated
     */
    private String plaevUsuarioModificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAED_FECHA_MODIFICACION
     *
     * @mbg.generated
     */
    private Date plaedFechaModificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_PACKINGLIST_AEREO.PLAEN_ESTADO
     *
     * @mbg.generated
     */
    private Short plaenEstado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_ID
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEN_ID
     *
     * @mbg.generated
     */
    public Integer getPlaenId() {
        return plaenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_ID
     *
     * @param plaenId the value for COMEXST_PACKINGLIST_AEREO.PLAEN_ID
     *
     * @mbg.generated
     */
    public void setPlaenId(Integer plaenId) {
        this.plaenId = plaenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_ID_EXPORTACION
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEN_ID_EXPORTACION
     *
     * @mbg.generated
     */
    public Integer getPlaenIdExportacion() {
        return plaenIdExportacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_ID_EXPORTACION
     *
     * @param plaenIdExportacion the value for COMEXST_PACKINGLIST_AEREO.PLAEN_ID_EXPORTACION
     *
     * @mbg.generated
     */
    public void setPlaenIdExportacion(Integer plaenIdExportacion) {
        this.plaenIdExportacion = plaenIdExportacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_NUMERO
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEN_NUMERO
     *
     * @mbg.generated
     */
    public Integer getPlaenNumero() {
        return plaenNumero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_NUMERO
     *
     * @param plaenNumero the value for COMEXST_PACKINGLIST_AEREO.PLAEN_NUMERO
     *
     * @mbg.generated
     */
    public void setPlaenNumero(Integer plaenNumero) {
        this.plaenNumero = plaenNumero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEV_CODIGO
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEV_CODIGO
     *
     * @mbg.generated
     */
    public String getPlaevCodigo() {
        return plaevCodigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEV_CODIGO
     *
     * @param plaevCodigo the value for COMEXST_PACKINGLIST_AEREO.PLAEV_CODIGO
     *
     * @mbg.generated
     */
    public void setPlaevCodigo(String plaevCodigo) {
        this.plaevCodigo = plaevCodigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEV_MATERIAL
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEV_MATERIAL
     *
     * @mbg.generated
     */
    public String getPlaevMaterial() {
        return plaevMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEV_MATERIAL
     *
     * @param plaevMaterial the value for COMEXST_PACKINGLIST_AEREO.PLAEV_MATERIAL
     *
     * @mbg.generated
     */
    public void setPlaevMaterial(String plaevMaterial) {
        this.plaevMaterial = plaevMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_CANTIDAD
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEN_CANTIDAD
     *
     * @mbg.generated
     */
    public Integer getPlaenCantidad() {
        return plaenCantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_CANTIDAD
     *
     * @param plaenCantidad the value for COMEXST_PACKINGLIST_AEREO.PLAEN_CANTIDAD
     *
     * @mbg.generated
     */
    public void setPlaenCantidad(Integer plaenCantidad) {
        this.plaenCantidad = plaenCantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_PESO_BRUTO
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEN_PESO_BRUTO
     *
     * @mbg.generated
     */
    public BigDecimal getPlaenPesoBruto() {
        return plaenPesoBruto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_PESO_BRUTO
     *
     * @param plaenPesoBruto the value for COMEXST_PACKINGLIST_AEREO.PLAEN_PESO_BRUTO
     *
     * @mbg.generated
     */
    public void setPlaenPesoBruto(BigDecimal plaenPesoBruto) {
        this.plaenPesoBruto = plaenPesoBruto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEV_DIMENSION
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEV_DIMENSION
     *
     * @mbg.generated
     */
    public String getPlaevDimension() {
        return plaevDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEV_DIMENSION
     *
     * @param plaevDimension the value for COMEXST_PACKINGLIST_AEREO.PLAEV_DIMENSION
     *
     * @mbg.generated
     */
    public void setPlaevDimension(String plaevDimension) {
        this.plaevDimension = plaevDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEV_USUARIO_CREACION
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEV_USUARIO_CREACION
     *
     * @mbg.generated
     */
    public String getPlaevUsuarioCreacion() {
        return plaevUsuarioCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEV_USUARIO_CREACION
     *
     * @param plaevUsuarioCreacion the value for COMEXST_PACKINGLIST_AEREO.PLAEV_USUARIO_CREACION
     *
     * @mbg.generated
     */
    public void setPlaevUsuarioCreacion(String plaevUsuarioCreacion) {
        this.plaevUsuarioCreacion = plaevUsuarioCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAED_FECHA_CREACION
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAED_FECHA_CREACION
     *
     * @mbg.generated
     */
    public Date getPlaedFechaCreacion() {
        return plaedFechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAED_FECHA_CREACION
     *
     * @param plaedFechaCreacion the value for COMEXST_PACKINGLIST_AEREO.PLAED_FECHA_CREACION
     *
     * @mbg.generated
     */
    public void setPlaedFechaCreacion(Date plaedFechaCreacion) {
        this.plaedFechaCreacion = plaedFechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEV_USUARIO_MODIFICACION
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEV_USUARIO_MODIFICACION
     *
     * @mbg.generated
     */
    public String getPlaevUsuarioModificacion() {
        return plaevUsuarioModificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEV_USUARIO_MODIFICACION
     *
     * @param plaevUsuarioModificacion the value for COMEXST_PACKINGLIST_AEREO.PLAEV_USUARIO_MODIFICACION
     *
     * @mbg.generated
     */
    public void setPlaevUsuarioModificacion(String plaevUsuarioModificacion) {
        this.plaevUsuarioModificacion = plaevUsuarioModificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAED_FECHA_MODIFICACION
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAED_FECHA_MODIFICACION
     *
     * @mbg.generated
     */
    public Date getPlaedFechaModificacion() {
        return plaedFechaModificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAED_FECHA_MODIFICACION
     *
     * @param plaedFechaModificacion the value for COMEXST_PACKINGLIST_AEREO.PLAED_FECHA_MODIFICACION
     *
     * @mbg.generated
     */
    public void setPlaedFechaModificacion(Date plaedFechaModificacion) {
        this.plaedFechaModificacion = plaedFechaModificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_ESTADO
     *
     * @return the value of COMEXST_PACKINGLIST_AEREO.PLAEN_ESTADO
     *
     * @mbg.generated
     */
    public Short getPlaenEstado() {
        return plaenEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_PACKINGLIST_AEREO.PLAEN_ESTADO
     *
     * @param plaenEstado the value for COMEXST_PACKINGLIST_AEREO.PLAEN_ESTADO
     *
     * @mbg.generated
     */
    public void setPlaenEstado(Short plaenEstado) {
        this.plaenEstado = plaenEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", plaenId=").append(plaenId);
        sb.append(", plaenIdExportacion=").append(plaenIdExportacion);
        sb.append(", plaenNumero=").append(plaenNumero);
        sb.append(", plaevCodigo=").append(plaevCodigo);
        sb.append(", plaevMaterial=").append(plaevMaterial);
        sb.append(", plaenCantidad=").append(plaenCantidad);
        sb.append(", plaenPesoBruto=").append(plaenPesoBruto);
        sb.append(", plaevDimension=").append(plaevDimension);
        sb.append(", plaevUsuarioCreacion=").append(plaevUsuarioCreacion);
        sb.append(", plaedFechaCreacion=").append(plaedFechaCreacion);
        sb.append(", plaevUsuarioModificacion=").append(plaevUsuarioModificacion);
        sb.append(", plaedFechaModificacion=").append(plaedFechaModificacion);
        sb.append(", plaenEstado=").append(plaenEstado);
        sb.append("]");
        return sb.toString();
    }
}