package com.caasa.comexsap.exportaciones.model.domain;

import java.util.Date;

public class ComexstCliente {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEN_ID
     *
     * @mbg.generated
     */
    private Integer clienId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_CODIGOSAP
     *
     * @mbg.generated
     */
    private String clievCodigosap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_NOMBRE
     *
     * @mbg.generated
     */
    private String clievNombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_NOMBRE2
     *
     * @mbg.generated
     */
    private String clievNombre2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_NOMBRE3
     *
     * @mbg.generated
     */
    private String clievNombre3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_CALLE
     *
     * @mbg.generated
     */
    private String clievCalle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_CALLE2
     *
     * @mbg.generated
     */
    private String clievCalle2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_CALLE3
     *
     * @mbg.generated
     */
    private String clievCalle3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_CODIGOPAIS
     *
     * @mbg.generated
     */
    private String clievCodigopais;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_DESCRIPCIONPAIS
     *
     * @mbg.generated
     */
    private String clievDescripcionpais;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_NUMEROIDENTFISCAL
     *
     * @mbg.generated
     */
    private String clievNumeroidentfiscal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_DISTRITO
     *
     * @mbg.generated
     */
    private String clievDistrito;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_POBLACION
     *
     * @mbg.generated
     */
    private String clievPoblacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_CODIGOREGION
     *
     * @mbg.generated
     */
    private String clievCodigoregion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_DESCRIPCIONREGION
     *
     * @mbg.generated
     */
    private String clievDescripcionregion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_DIRECCION
     *
     * @mbg.generated
     */
    private String clievDireccion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_CORREO
     *
     * @mbg.generated
     */
    private String clievCorreo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEN_LINEACREDITODISPONIBLE
     *
     * @mbg.generated
     */
    private Short clienLineacreditodisponible;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_INCOTERM
     *
     * @mbg.generated
     */
    private String clievIncoterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_MONEDA
     *
     * @mbg.generated
     */
    private String clievMoneda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_CONDICIONPAGO
     *
     * @mbg.generated
     */
    private String clievCondicionpago;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_LISTAPRECIO
     *
     * @mbg.generated
     */
    private String clievListaprecio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_RUC
     *
     * @mbg.generated
     */
    private String clievRuc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_USUARIOCREACION
     *
     * @mbg.generated
     */
    private String clievUsuariocreacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIED_FECHACREACION
     *
     * @mbg.generated
     */
    private Date cliedFechacreacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEV_USUARIOMODIFICACION
     *
     * @mbg.generated
     */
    private String clievUsuariomodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIED_FECHAMODIFICACION
     *
     * @mbg.generated
     */
    private Date cliedFechamodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE.CLIEN_ESTADO
     *
     * @mbg.generated
     */
    private Short clienEstado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEN_ID
     *
     * @return the value of COMEXST_CLIENTE.CLIEN_ID
     *
     * @mbg.generated
     */
    public Integer getClienId() {
        return clienId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEN_ID
     *
     * @param clienId the value for COMEXST_CLIENTE.CLIEN_ID
     *
     * @mbg.generated
     */
    public void setClienId(Integer clienId) {
        this.clienId = clienId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_CODIGOSAP
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_CODIGOSAP
     *
     * @mbg.generated
     */
    public String getClievCodigosap() {
        return clievCodigosap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_CODIGOSAP
     *
     * @param clievCodigosap the value for COMEXST_CLIENTE.CLIEV_CODIGOSAP
     *
     * @mbg.generated
     */
    public void setClievCodigosap(String clievCodigosap) {
        this.clievCodigosap = clievCodigosap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_NOMBRE
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_NOMBRE
     *
     * @mbg.generated
     */
    public String getClievNombre() {
        return clievNombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_NOMBRE
     *
     * @param clievNombre the value for COMEXST_CLIENTE.CLIEV_NOMBRE
     *
     * @mbg.generated
     */
    public void setClievNombre(String clievNombre) {
        this.clievNombre = clievNombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_NOMBRE2
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_NOMBRE2
     *
     * @mbg.generated
     */
    public String getClievNombre2() {
        return clievNombre2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_NOMBRE2
     *
     * @param clievNombre2 the value for COMEXST_CLIENTE.CLIEV_NOMBRE2
     *
     * @mbg.generated
     */
    public void setClievNombre2(String clievNombre2) {
        this.clievNombre2 = clievNombre2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_NOMBRE3
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_NOMBRE3
     *
     * @mbg.generated
     */
    public String getClievNombre3() {
        return clievNombre3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_NOMBRE3
     *
     * @param clievNombre3 the value for COMEXST_CLIENTE.CLIEV_NOMBRE3
     *
     * @mbg.generated
     */
    public void setClievNombre3(String clievNombre3) {
        this.clievNombre3 = clievNombre3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_CALLE
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_CALLE
     *
     * @mbg.generated
     */
    public String getClievCalle() {
        return clievCalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_CALLE
     *
     * @param clievCalle the value for COMEXST_CLIENTE.CLIEV_CALLE
     *
     * @mbg.generated
     */
    public void setClievCalle(String clievCalle) {
        this.clievCalle = clievCalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_CALLE2
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_CALLE2
     *
     * @mbg.generated
     */
    public String getClievCalle2() {
        return clievCalle2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_CALLE2
     *
     * @param clievCalle2 the value for COMEXST_CLIENTE.CLIEV_CALLE2
     *
     * @mbg.generated
     */
    public void setClievCalle2(String clievCalle2) {
        this.clievCalle2 = clievCalle2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_CALLE3
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_CALLE3
     *
     * @mbg.generated
     */
    public String getClievCalle3() {
        return clievCalle3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_CALLE3
     *
     * @param clievCalle3 the value for COMEXST_CLIENTE.CLIEV_CALLE3
     *
     * @mbg.generated
     */
    public void setClievCalle3(String clievCalle3) {
        this.clievCalle3 = clievCalle3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_CODIGOPAIS
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_CODIGOPAIS
     *
     * @mbg.generated
     */
    public String getClievCodigopais() {
        return clievCodigopais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_CODIGOPAIS
     *
     * @param clievCodigopais the value for COMEXST_CLIENTE.CLIEV_CODIGOPAIS
     *
     * @mbg.generated
     */
    public void setClievCodigopais(String clievCodigopais) {
        this.clievCodigopais = clievCodigopais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_DESCRIPCIONPAIS
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_DESCRIPCIONPAIS
     *
     * @mbg.generated
     */
    public String getClievDescripcionpais() {
        return clievDescripcionpais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_DESCRIPCIONPAIS
     *
     * @param clievDescripcionpais the value for COMEXST_CLIENTE.CLIEV_DESCRIPCIONPAIS
     *
     * @mbg.generated
     */
    public void setClievDescripcionpais(String clievDescripcionpais) {
        this.clievDescripcionpais = clievDescripcionpais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_NUMEROIDENTFISCAL
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_NUMEROIDENTFISCAL
     *
     * @mbg.generated
     */
    public String getClievNumeroidentfiscal() {
        return clievNumeroidentfiscal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_NUMEROIDENTFISCAL
     *
     * @param clievNumeroidentfiscal the value for COMEXST_CLIENTE.CLIEV_NUMEROIDENTFISCAL
     *
     * @mbg.generated
     */
    public void setClievNumeroidentfiscal(String clievNumeroidentfiscal) {
        this.clievNumeroidentfiscal = clievNumeroidentfiscal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_DISTRITO
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_DISTRITO
     *
     * @mbg.generated
     */
    public String getClievDistrito() {
        return clievDistrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_DISTRITO
     *
     * @param clievDistrito the value for COMEXST_CLIENTE.CLIEV_DISTRITO
     *
     * @mbg.generated
     */
    public void setClievDistrito(String clievDistrito) {
        this.clievDistrito = clievDistrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_POBLACION
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_POBLACION
     *
     * @mbg.generated
     */
    public String getClievPoblacion() {
        return clievPoblacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_POBLACION
     *
     * @param clievPoblacion the value for COMEXST_CLIENTE.CLIEV_POBLACION
     *
     * @mbg.generated
     */
    public void setClievPoblacion(String clievPoblacion) {
        this.clievPoblacion = clievPoblacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_CODIGOREGION
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_CODIGOREGION
     *
     * @mbg.generated
     */
    public String getClievCodigoregion() {
        return clievCodigoregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_CODIGOREGION
     *
     * @param clievCodigoregion the value for COMEXST_CLIENTE.CLIEV_CODIGOREGION
     *
     * @mbg.generated
     */
    public void setClievCodigoregion(String clievCodigoregion) {
        this.clievCodigoregion = clievCodigoregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_DESCRIPCIONREGION
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_DESCRIPCIONREGION
     *
     * @mbg.generated
     */
    public String getClievDescripcionregion() {
        return clievDescripcionregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_DESCRIPCIONREGION
     *
     * @param clievDescripcionregion the value for COMEXST_CLIENTE.CLIEV_DESCRIPCIONREGION
     *
     * @mbg.generated
     */
    public void setClievDescripcionregion(String clievDescripcionregion) {
        this.clievDescripcionregion = clievDescripcionregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_DIRECCION
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_DIRECCION
     *
     * @mbg.generated
     */
    public String getClievDireccion() {
        return clievDireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_DIRECCION
     *
     * @param clievDireccion the value for COMEXST_CLIENTE.CLIEV_DIRECCION
     *
     * @mbg.generated
     */
    public void setClievDireccion(String clievDireccion) {
        this.clievDireccion = clievDireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_CORREO
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_CORREO
     *
     * @mbg.generated
     */
    public String getClievCorreo() {
        return clievCorreo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_CORREO
     *
     * @param clievCorreo the value for COMEXST_CLIENTE.CLIEV_CORREO
     *
     * @mbg.generated
     */
    public void setClievCorreo(String clievCorreo) {
        this.clievCorreo = clievCorreo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEN_LINEACREDITODISPONIBLE
     *
     * @return the value of COMEXST_CLIENTE.CLIEN_LINEACREDITODISPONIBLE
     *
     * @mbg.generated
     */
    public Short getClienLineacreditodisponible() {
        return clienLineacreditodisponible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEN_LINEACREDITODISPONIBLE
     *
     * @param clienLineacreditodisponible the value for COMEXST_CLIENTE.CLIEN_LINEACREDITODISPONIBLE
     *
     * @mbg.generated
     */
    public void setClienLineacreditodisponible(Short clienLineacreditodisponible) {
        this.clienLineacreditodisponible = clienLineacreditodisponible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_INCOTERM
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_INCOTERM
     *
     * @mbg.generated
     */
    public String getClievIncoterm() {
        return clievIncoterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_INCOTERM
     *
     * @param clievIncoterm the value for COMEXST_CLIENTE.CLIEV_INCOTERM
     *
     * @mbg.generated
     */
    public void setClievIncoterm(String clievIncoterm) {
        this.clievIncoterm = clievIncoterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_MONEDA
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_MONEDA
     *
     * @mbg.generated
     */
    public String getClievMoneda() {
        return clievMoneda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_MONEDA
     *
     * @param clievMoneda the value for COMEXST_CLIENTE.CLIEV_MONEDA
     *
     * @mbg.generated
     */
    public void setClievMoneda(String clievMoneda) {
        this.clievMoneda = clievMoneda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_CONDICIONPAGO
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_CONDICIONPAGO
     *
     * @mbg.generated
     */
    public String getClievCondicionpago() {
        return clievCondicionpago;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_CONDICIONPAGO
     *
     * @param clievCondicionpago the value for COMEXST_CLIENTE.CLIEV_CONDICIONPAGO
     *
     * @mbg.generated
     */
    public void setClievCondicionpago(String clievCondicionpago) {
        this.clievCondicionpago = clievCondicionpago;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_LISTAPRECIO
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_LISTAPRECIO
     *
     * @mbg.generated
     */
    public String getClievListaprecio() {
        return clievListaprecio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_LISTAPRECIO
     *
     * @param clievListaprecio the value for COMEXST_CLIENTE.CLIEV_LISTAPRECIO
     *
     * @mbg.generated
     */
    public void setClievListaprecio(String clievListaprecio) {
        this.clievListaprecio = clievListaprecio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_RUC
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_RUC
     *
     * @mbg.generated
     */
    public String getClievRuc() {
        return clievRuc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_RUC
     *
     * @param clievRuc the value for COMEXST_CLIENTE.CLIEV_RUC
     *
     * @mbg.generated
     */
    public void setClievRuc(String clievRuc) {
        this.clievRuc = clievRuc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_USUARIOCREACION
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_USUARIOCREACION
     *
     * @mbg.generated
     */
    public String getClievUsuariocreacion() {
        return clievUsuariocreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_USUARIOCREACION
     *
     * @param clievUsuariocreacion the value for COMEXST_CLIENTE.CLIEV_USUARIOCREACION
     *
     * @mbg.generated
     */
    public void setClievUsuariocreacion(String clievUsuariocreacion) {
        this.clievUsuariocreacion = clievUsuariocreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIED_FECHACREACION
     *
     * @return the value of COMEXST_CLIENTE.CLIED_FECHACREACION
     *
     * @mbg.generated
     */
    public Date getCliedFechacreacion() {
        return cliedFechacreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIED_FECHACREACION
     *
     * @param cliedFechacreacion the value for COMEXST_CLIENTE.CLIED_FECHACREACION
     *
     * @mbg.generated
     */
    public void setCliedFechacreacion(Date cliedFechacreacion) {
        this.cliedFechacreacion = cliedFechacreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEV_USUARIOMODIFICACION
     *
     * @return the value of COMEXST_CLIENTE.CLIEV_USUARIOMODIFICACION
     *
     * @mbg.generated
     */
    public String getClievUsuariomodificacion() {
        return clievUsuariomodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEV_USUARIOMODIFICACION
     *
     * @param clievUsuariomodificacion the value for COMEXST_CLIENTE.CLIEV_USUARIOMODIFICACION
     *
     * @mbg.generated
     */
    public void setClievUsuariomodificacion(String clievUsuariomodificacion) {
        this.clievUsuariomodificacion = clievUsuariomodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIED_FECHAMODIFICACION
     *
     * @return the value of COMEXST_CLIENTE.CLIED_FECHAMODIFICACION
     *
     * @mbg.generated
     */
    public Date getCliedFechamodificacion() {
        return cliedFechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIED_FECHAMODIFICACION
     *
     * @param cliedFechamodificacion the value for COMEXST_CLIENTE.CLIED_FECHAMODIFICACION
     *
     * @mbg.generated
     */
    public void setCliedFechamodificacion(Date cliedFechamodificacion) {
        this.cliedFechamodificacion = cliedFechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE.CLIEN_ESTADO
     *
     * @return the value of COMEXST_CLIENTE.CLIEN_ESTADO
     *
     * @mbg.generated
     */
    public Short getClienEstado() {
        return clienEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE.CLIEN_ESTADO
     *
     * @param clienEstado the value for COMEXST_CLIENTE.CLIEN_ESTADO
     *
     * @mbg.generated
     */
    public void setClienEstado(Short clienEstado) {
        this.clienEstado = clienEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clienId=").append(clienId);
        sb.append(", clievCodigosap=").append(clievCodigosap);
        sb.append(", clievNombre=").append(clievNombre);
        sb.append(", clievNombre2=").append(clievNombre2);
        sb.append(", clievNombre3=").append(clievNombre3);
        sb.append(", clievCalle=").append(clievCalle);
        sb.append(", clievCalle2=").append(clievCalle2);
        sb.append(", clievCalle3=").append(clievCalle3);
        sb.append(", clievCodigopais=").append(clievCodigopais);
        sb.append(", clievDescripcionpais=").append(clievDescripcionpais);
        sb.append(", clievNumeroidentfiscal=").append(clievNumeroidentfiscal);
        sb.append(", clievDistrito=").append(clievDistrito);
        sb.append(", clievPoblacion=").append(clievPoblacion);
        sb.append(", clievCodigoregion=").append(clievCodigoregion);
        sb.append(", clievDescripcionregion=").append(clievDescripcionregion);
        sb.append(", clievDireccion=").append(clievDireccion);
        sb.append(", clievCorreo=").append(clievCorreo);
        sb.append(", clienLineacreditodisponible=").append(clienLineacreditodisponible);
        sb.append(", clievIncoterm=").append(clievIncoterm);
        sb.append(", clievMoneda=").append(clievMoneda);
        sb.append(", clievCondicionpago=").append(clievCondicionpago);
        sb.append(", clievListaprecio=").append(clievListaprecio);
        sb.append(", clievRuc=").append(clievRuc);
        sb.append(", clievUsuariocreacion=").append(clievUsuariocreacion);
        sb.append(", cliedFechacreacion=").append(cliedFechacreacion);
        sb.append(", clievUsuariomodificacion=").append(clievUsuariomodificacion);
        sb.append(", cliedFechamodificacion=").append(cliedFechamodificacion);
        sb.append(", clienEstado=").append(clienEstado);
        sb.append("]");
        return sb.toString();
    }
}