package com.caasa.comexsap.exportaciones.model.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ComexstEtiquetaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public ComexstEtiquetaExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEtiqnIdIsNull() {
            addCriterion("ETIQN_ID is null");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdIsNotNull() {
            addCriterion("ETIQN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdEqualTo(Integer value) {
            addCriterion("ETIQN_ID =", value, "etiqnId");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdNotEqualTo(Integer value) {
            addCriterion("ETIQN_ID <>", value, "etiqnId");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdGreaterThan(Integer value) {
            addCriterion("ETIQN_ID >", value, "etiqnId");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ETIQN_ID >=", value, "etiqnId");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdLessThan(Integer value) {
            addCriterion("ETIQN_ID <", value, "etiqnId");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdLessThanOrEqualTo(Integer value) {
            addCriterion("ETIQN_ID <=", value, "etiqnId");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdIn(List<Integer> values) {
            addCriterion("ETIQN_ID in", values, "etiqnId");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdNotIn(List<Integer> values) {
            addCriterion("ETIQN_ID not in", values, "etiqnId");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdBetween(Integer value1, Integer value2) {
            addCriterion("ETIQN_ID between", value1, value2, "etiqnId");
            return (Criteria) this;
        }

        public Criteria andEtiqnIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ETIQN_ID not between", value1, value2, "etiqnId");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreIsNull() {
            addCriterion("ETIQV_NOMBRE is null");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreIsNotNull() {
            addCriterion("ETIQV_NOMBRE is not null");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreEqualTo(String value) {
            addCriterion("ETIQV_NOMBRE =", value, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreNotEqualTo(String value) {
            addCriterion("ETIQV_NOMBRE <>", value, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreGreaterThan(String value) {
            addCriterion("ETIQV_NOMBRE >", value, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreGreaterThanOrEqualTo(String value) {
            addCriterion("ETIQV_NOMBRE >=", value, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreLessThan(String value) {
            addCriterion("ETIQV_NOMBRE <", value, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreLessThanOrEqualTo(String value) {
            addCriterion("ETIQV_NOMBRE <=", value, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreLike(String value) {
            addCriterion("ETIQV_NOMBRE like", value, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreNotLike(String value) {
            addCriterion("ETIQV_NOMBRE not like", value, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreIn(List<String> values) {
            addCriterion("ETIQV_NOMBRE in", values, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreNotIn(List<String> values) {
            addCriterion("ETIQV_NOMBRE not in", values, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreBetween(String value1, String value2) {
            addCriterion("ETIQV_NOMBRE between", value1, value2, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreNotBetween(String value1, String value2) {
            addCriterion("ETIQV_NOMBRE not between", value1, value2, "etiqvNombre");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesIsNull() {
            addCriterion("ETIQV_NOMBRE_INGLES is null");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesIsNotNull() {
            addCriterion("ETIQV_NOMBRE_INGLES is not null");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesEqualTo(String value) {
            addCriterion("ETIQV_NOMBRE_INGLES =", value, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesNotEqualTo(String value) {
            addCriterion("ETIQV_NOMBRE_INGLES <>", value, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesGreaterThan(String value) {
            addCriterion("ETIQV_NOMBRE_INGLES >", value, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesGreaterThanOrEqualTo(String value) {
            addCriterion("ETIQV_NOMBRE_INGLES >=", value, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesLessThan(String value) {
            addCriterion("ETIQV_NOMBRE_INGLES <", value, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesLessThanOrEqualTo(String value) {
            addCriterion("ETIQV_NOMBRE_INGLES <=", value, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesLike(String value) {
            addCriterion("ETIQV_NOMBRE_INGLES like", value, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesNotLike(String value) {
            addCriterion("ETIQV_NOMBRE_INGLES not like", value, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesIn(List<String> values) {
            addCriterion("ETIQV_NOMBRE_INGLES in", values, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesNotIn(List<String> values) {
            addCriterion("ETIQV_NOMBRE_INGLES not in", values, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesBetween(String value1, String value2) {
            addCriterion("ETIQV_NOMBRE_INGLES between", value1, value2, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvNombreInglesNotBetween(String value1, String value2) {
            addCriterion("ETIQV_NOMBRE_INGLES not between", value1, value2, "etiqvNombreIngles");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionIsNull() {
            addCriterion("ETIQV_USUARIO_CREACION is null");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionIsNotNull() {
            addCriterion("ETIQV_USUARIO_CREACION is not null");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionEqualTo(String value) {
            addCriterion("ETIQV_USUARIO_CREACION =", value, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionNotEqualTo(String value) {
            addCriterion("ETIQV_USUARIO_CREACION <>", value, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionGreaterThan(String value) {
            addCriterion("ETIQV_USUARIO_CREACION >", value, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionGreaterThanOrEqualTo(String value) {
            addCriterion("ETIQV_USUARIO_CREACION >=", value, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionLessThan(String value) {
            addCriterion("ETIQV_USUARIO_CREACION <", value, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionLessThanOrEqualTo(String value) {
            addCriterion("ETIQV_USUARIO_CREACION <=", value, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionLike(String value) {
            addCriterion("ETIQV_USUARIO_CREACION like", value, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionNotLike(String value) {
            addCriterion("ETIQV_USUARIO_CREACION not like", value, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionIn(List<String> values) {
            addCriterion("ETIQV_USUARIO_CREACION in", values, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionNotIn(List<String> values) {
            addCriterion("ETIQV_USUARIO_CREACION not in", values, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionBetween(String value1, String value2) {
            addCriterion("ETIQV_USUARIO_CREACION between", value1, value2, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioCreacionNotBetween(String value1, String value2) {
            addCriterion("ETIQV_USUARIO_CREACION not between", value1, value2, "etiqvUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionIsNull() {
            addCriterion("ETIQD_FECHA_CREACION is null");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionIsNotNull() {
            addCriterion("ETIQD_FECHA_CREACION is not null");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionEqualTo(Date value) {
            addCriterion("ETIQD_FECHA_CREACION =", value, "etiqdFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionNotEqualTo(Date value) {
            addCriterion("ETIQD_FECHA_CREACION <>", value, "etiqdFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionGreaterThan(Date value) {
            addCriterion("ETIQD_FECHA_CREACION >", value, "etiqdFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionGreaterThanOrEqualTo(Date value) {
            addCriterion("ETIQD_FECHA_CREACION >=", value, "etiqdFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionLessThan(Date value) {
            addCriterion("ETIQD_FECHA_CREACION <", value, "etiqdFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionLessThanOrEqualTo(Date value) {
            addCriterion("ETIQD_FECHA_CREACION <=", value, "etiqdFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionIn(List<Date> values) {
            addCriterion("ETIQD_FECHA_CREACION in", values, "etiqdFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionNotIn(List<Date> values) {
            addCriterion("ETIQD_FECHA_CREACION not in", values, "etiqdFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionBetween(Date value1, Date value2) {
            addCriterion("ETIQD_FECHA_CREACION between", value1, value2, "etiqdFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaCreacionNotBetween(Date value1, Date value2) {
            addCriterion("ETIQD_FECHA_CREACION not between", value1, value2, "etiqdFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionIsNull() {
            addCriterion("ETIQV_USUARIO_MODIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionIsNotNull() {
            addCriterion("ETIQV_USUARIO_MODIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionEqualTo(String value) {
            addCriterion("ETIQV_USUARIO_MODIFICACION =", value, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionNotEqualTo(String value) {
            addCriterion("ETIQV_USUARIO_MODIFICACION <>", value, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionGreaterThan(String value) {
            addCriterion("ETIQV_USUARIO_MODIFICACION >", value, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionGreaterThanOrEqualTo(String value) {
            addCriterion("ETIQV_USUARIO_MODIFICACION >=", value, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionLessThan(String value) {
            addCriterion("ETIQV_USUARIO_MODIFICACION <", value, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionLessThanOrEqualTo(String value) {
            addCriterion("ETIQV_USUARIO_MODIFICACION <=", value, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionLike(String value) {
            addCriterion("ETIQV_USUARIO_MODIFICACION like", value, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionNotLike(String value) {
            addCriterion("ETIQV_USUARIO_MODIFICACION not like", value, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionIn(List<String> values) {
            addCriterion("ETIQV_USUARIO_MODIFICACION in", values, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionNotIn(List<String> values) {
            addCriterion("ETIQV_USUARIO_MODIFICACION not in", values, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionBetween(String value1, String value2) {
            addCriterion("ETIQV_USUARIO_MODIFICACION between", value1, value2, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqvUsuarioModificacionNotBetween(String value1, String value2) {
            addCriterion("ETIQV_USUARIO_MODIFICACION not between", value1, value2, "etiqvUsuarioModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionIsNull() {
            addCriterion("ETIQD_FECHA_MODIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionIsNotNull() {
            addCriterion("ETIQD_FECHA_MODIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionEqualTo(Date value) {
            addCriterion("ETIQD_FECHA_MODIFICACION =", value, "etiqdFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionNotEqualTo(Date value) {
            addCriterion("ETIQD_FECHA_MODIFICACION <>", value, "etiqdFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionGreaterThan(Date value) {
            addCriterion("ETIQD_FECHA_MODIFICACION >", value, "etiqdFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionGreaterThanOrEqualTo(Date value) {
            addCriterion("ETIQD_FECHA_MODIFICACION >=", value, "etiqdFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionLessThan(Date value) {
            addCriterion("ETIQD_FECHA_MODIFICACION <", value, "etiqdFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionLessThanOrEqualTo(Date value) {
            addCriterion("ETIQD_FECHA_MODIFICACION <=", value, "etiqdFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionIn(List<Date> values) {
            addCriterion("ETIQD_FECHA_MODIFICACION in", values, "etiqdFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionNotIn(List<Date> values) {
            addCriterion("ETIQD_FECHA_MODIFICACION not in", values, "etiqdFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionBetween(Date value1, Date value2) {
            addCriterion("ETIQD_FECHA_MODIFICACION between", value1, value2, "etiqdFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqdFechaModificacionNotBetween(Date value1, Date value2) {
            addCriterion("ETIQD_FECHA_MODIFICACION not between", value1, value2, "etiqdFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoIsNull() {
            addCriterion("ETIQN_ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoIsNotNull() {
            addCriterion("ETIQN_ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoEqualTo(Short value) {
            addCriterion("ETIQN_ESTADO =", value, "etiqnEstado");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoNotEqualTo(Short value) {
            addCriterion("ETIQN_ESTADO <>", value, "etiqnEstado");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoGreaterThan(Short value) {
            addCriterion("ETIQN_ESTADO >", value, "etiqnEstado");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoGreaterThanOrEqualTo(Short value) {
            addCriterion("ETIQN_ESTADO >=", value, "etiqnEstado");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoLessThan(Short value) {
            addCriterion("ETIQN_ESTADO <", value, "etiqnEstado");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoLessThanOrEqualTo(Short value) {
            addCriterion("ETIQN_ESTADO <=", value, "etiqnEstado");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoIn(List<Short> values) {
            addCriterion("ETIQN_ESTADO in", values, "etiqnEstado");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoNotIn(List<Short> values) {
            addCriterion("ETIQN_ESTADO not in", values, "etiqnEstado");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoBetween(Short value1, Short value2) {
            addCriterion("ETIQN_ESTADO between", value1, value2, "etiqnEstado");
            return (Criteria) this;
        }

        public Criteria andEtiqnEstadoNotBetween(Short value1, Short value2) {
            addCriterion("ETIQN_ESTADO not between", value1, value2, "etiqnEstado");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}