package com.caasa.comexsap.exportaciones.model.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ComexstFacturaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public ComexstFacturaExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFactnIdIsNull() {
            addCriterion("FACTN_ID is null");
            return (Criteria) this;
        }

        public Criteria andFactnIdIsNotNull() {
            addCriterion("FACTN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFactnIdEqualTo(Integer value) {
            addCriterion("FACTN_ID =", value, "factnId");
            return (Criteria) this;
        }

        public Criteria andFactnIdNotEqualTo(Integer value) {
            addCriterion("FACTN_ID <>", value, "factnId");
            return (Criteria) this;
        }

        public Criteria andFactnIdGreaterThan(Integer value) {
            addCriterion("FACTN_ID >", value, "factnId");
            return (Criteria) this;
        }

        public Criteria andFactnIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FACTN_ID >=", value, "factnId");
            return (Criteria) this;
        }

        public Criteria andFactnIdLessThan(Integer value) {
            addCriterion("FACTN_ID <", value, "factnId");
            return (Criteria) this;
        }

        public Criteria andFactnIdLessThanOrEqualTo(Integer value) {
            addCriterion("FACTN_ID <=", value, "factnId");
            return (Criteria) this;
        }

        public Criteria andFactnIdIn(List<Integer> values) {
            addCriterion("FACTN_ID in", values, "factnId");
            return (Criteria) this;
        }

        public Criteria andFactnIdNotIn(List<Integer> values) {
            addCriterion("FACTN_ID not in", values, "factnId");
            return (Criteria) this;
        }

        public Criteria andFactnIdBetween(Integer value1, Integer value2) {
            addCriterion("FACTN_ID between", value1, value2, "factnId");
            return (Criteria) this;
        }

        public Criteria andFactnIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FACTN_ID not between", value1, value2, "factnId");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapIsNull() {
            addCriterion("FACTV_CODIGOSAP is null");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapIsNotNull() {
            addCriterion("FACTV_CODIGOSAP is not null");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapEqualTo(String value) {
            addCriterion("FACTV_CODIGOSAP =", value, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapNotEqualTo(String value) {
            addCriterion("FACTV_CODIGOSAP <>", value, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapGreaterThan(String value) {
            addCriterion("FACTV_CODIGOSAP >", value, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_CODIGOSAP >=", value, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapLessThan(String value) {
            addCriterion("FACTV_CODIGOSAP <", value, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapLessThanOrEqualTo(String value) {
            addCriterion("FACTV_CODIGOSAP <=", value, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapLike(String value) {
            addCriterion("FACTV_CODIGOSAP like", value, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapNotLike(String value) {
            addCriterion("FACTV_CODIGOSAP not like", value, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapIn(List<String> values) {
            addCriterion("FACTV_CODIGOSAP in", values, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapNotIn(List<String> values) {
            addCriterion("FACTV_CODIGOSAP not in", values, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapBetween(String value1, String value2) {
            addCriterion("FACTV_CODIGOSAP between", value1, value2, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvCodigosapNotBetween(String value1, String value2) {
            addCriterion("FACTV_CODIGOSAP not between", value1, value2, "factvCodigosap");
            return (Criteria) this;
        }

        public Criteria andFactvSectorIsNull() {
            addCriterion("FACTV_SECTOR is null");
            return (Criteria) this;
        }

        public Criteria andFactvSectorIsNotNull() {
            addCriterion("FACTV_SECTOR is not null");
            return (Criteria) this;
        }

        public Criteria andFactvSectorEqualTo(String value) {
            addCriterion("FACTV_SECTOR =", value, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorNotEqualTo(String value) {
            addCriterion("FACTV_SECTOR <>", value, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorGreaterThan(String value) {
            addCriterion("FACTV_SECTOR >", value, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_SECTOR >=", value, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorLessThan(String value) {
            addCriterion("FACTV_SECTOR <", value, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorLessThanOrEqualTo(String value) {
            addCriterion("FACTV_SECTOR <=", value, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorLike(String value) {
            addCriterion("FACTV_SECTOR like", value, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorNotLike(String value) {
            addCriterion("FACTV_SECTOR not like", value, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorIn(List<String> values) {
            addCriterion("FACTV_SECTOR in", values, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorNotIn(List<String> values) {
            addCriterion("FACTV_SECTOR not in", values, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorBetween(String value1, String value2) {
            addCriterion("FACTV_SECTOR between", value1, value2, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvSectorNotBetween(String value1, String value2) {
            addCriterion("FACTV_SECTOR not between", value1, value2, "factvSector");
            return (Criteria) this;
        }

        public Criteria andFactvFolioIsNull() {
            addCriterion("FACTV_FOLIO is null");
            return (Criteria) this;
        }

        public Criteria andFactvFolioIsNotNull() {
            addCriterion("FACTV_FOLIO is not null");
            return (Criteria) this;
        }

        public Criteria andFactvFolioEqualTo(String value) {
            addCriterion("FACTV_FOLIO =", value, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioNotEqualTo(String value) {
            addCriterion("FACTV_FOLIO <>", value, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioGreaterThan(String value) {
            addCriterion("FACTV_FOLIO >", value, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_FOLIO >=", value, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioLessThan(String value) {
            addCriterion("FACTV_FOLIO <", value, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioLessThanOrEqualTo(String value) {
            addCriterion("FACTV_FOLIO <=", value, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioLike(String value) {
            addCriterion("FACTV_FOLIO like", value, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioNotLike(String value) {
            addCriterion("FACTV_FOLIO not like", value, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioIn(List<String> values) {
            addCriterion("FACTV_FOLIO in", values, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioNotIn(List<String> values) {
            addCriterion("FACTV_FOLIO not in", values, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioBetween(String value1, String value2) {
            addCriterion("FACTV_FOLIO between", value1, value2, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactvFolioNotBetween(String value1, String value2) {
            addCriterion("FACTV_FOLIO not between", value1, value2, "factvFolio");
            return (Criteria) this;
        }

        public Criteria andFactdFechaIsNull() {
            addCriterion("FACTD_FECHA is null");
            return (Criteria) this;
        }

        public Criteria andFactdFechaIsNotNull() {
            addCriterion("FACTD_FECHA is not null");
            return (Criteria) this;
        }

        public Criteria andFactdFechaEqualTo(Date value) {
            addCriterion("FACTD_FECHA =", value, "factdFecha");
            return (Criteria) this;
        }

        public Criteria andFactdFechaNotEqualTo(Date value) {
            addCriterion("FACTD_FECHA <>", value, "factdFecha");
            return (Criteria) this;
        }

        public Criteria andFactdFechaGreaterThan(Date value) {
            addCriterion("FACTD_FECHA >", value, "factdFecha");
            return (Criteria) this;
        }

        public Criteria andFactdFechaGreaterThanOrEqualTo(Date value) {
            addCriterion("FACTD_FECHA >=", value, "factdFecha");
            return (Criteria) this;
        }

        public Criteria andFactdFechaLessThan(Date value) {
            addCriterion("FACTD_FECHA <", value, "factdFecha");
            return (Criteria) this;
        }

        public Criteria andFactdFechaLessThanOrEqualTo(Date value) {
            addCriterion("FACTD_FECHA <=", value, "factdFecha");
            return (Criteria) this;
        }

        public Criteria andFactdFechaIn(List<Date> values) {
            addCriterion("FACTD_FECHA in", values, "factdFecha");
            return (Criteria) this;
        }

        public Criteria andFactdFechaNotIn(List<Date> values) {
            addCriterion("FACTD_FECHA not in", values, "factdFecha");
            return (Criteria) this;
        }

        public Criteria andFactdFechaBetween(Date value1, Date value2) {
            addCriterion("FACTD_FECHA between", value1, value2, "factdFecha");
            return (Criteria) this;
        }

        public Criteria andFactdFechaNotBetween(Date value1, Date value2) {
            addCriterion("FACTD_FECHA not between", value1, value2, "factdFecha");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatIsNull() {
            addCriterion("FACTV_HORASUNAT is null");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatIsNotNull() {
            addCriterion("FACTV_HORASUNAT is not null");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatEqualTo(String value) {
            addCriterion("FACTV_HORASUNAT =", value, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatNotEqualTo(String value) {
            addCriterion("FACTV_HORASUNAT <>", value, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatGreaterThan(String value) {
            addCriterion("FACTV_HORASUNAT >", value, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_HORASUNAT >=", value, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatLessThan(String value) {
            addCriterion("FACTV_HORASUNAT <", value, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatLessThanOrEqualTo(String value) {
            addCriterion("FACTV_HORASUNAT <=", value, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatLike(String value) {
            addCriterion("FACTV_HORASUNAT like", value, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatNotLike(String value) {
            addCriterion("FACTV_HORASUNAT not like", value, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatIn(List<String> values) {
            addCriterion("FACTV_HORASUNAT in", values, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatNotIn(List<String> values) {
            addCriterion("FACTV_HORASUNAT not in", values, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatBetween(String value1, String value2) {
            addCriterion("FACTV_HORASUNAT between", value1, value2, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactvHorasunatNotBetween(String value1, String value2) {
            addCriterion("FACTV_HORASUNAT not between", value1, value2, "factvHorasunat");
            return (Criteria) this;
        }

        public Criteria andFactnImporteIsNull() {
            addCriterion("FACTN_IMPORTE is null");
            return (Criteria) this;
        }

        public Criteria andFactnImporteIsNotNull() {
            addCriterion("FACTN_IMPORTE is not null");
            return (Criteria) this;
        }

        public Criteria andFactnImporteEqualTo(BigDecimal value) {
            addCriterion("FACTN_IMPORTE =", value, "factnImporte");
            return (Criteria) this;
        }

        public Criteria andFactnImporteNotEqualTo(BigDecimal value) {
            addCriterion("FACTN_IMPORTE <>", value, "factnImporte");
            return (Criteria) this;
        }

        public Criteria andFactnImporteGreaterThan(BigDecimal value) {
            addCriterion("FACTN_IMPORTE >", value, "factnImporte");
            return (Criteria) this;
        }

        public Criteria andFactnImporteGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FACTN_IMPORTE >=", value, "factnImporte");
            return (Criteria) this;
        }

        public Criteria andFactnImporteLessThan(BigDecimal value) {
            addCriterion("FACTN_IMPORTE <", value, "factnImporte");
            return (Criteria) this;
        }

        public Criteria andFactnImporteLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FACTN_IMPORTE <=", value, "factnImporte");
            return (Criteria) this;
        }

        public Criteria andFactnImporteIn(List<BigDecimal> values) {
            addCriterion("FACTN_IMPORTE in", values, "factnImporte");
            return (Criteria) this;
        }

        public Criteria andFactnImporteNotIn(List<BigDecimal> values) {
            addCriterion("FACTN_IMPORTE not in", values, "factnImporte");
            return (Criteria) this;
        }

        public Criteria andFactnImporteBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FACTN_IMPORTE between", value1, value2, "factnImporte");
            return (Criteria) this;
        }

        public Criteria andFactnImporteNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FACTN_IMPORTE not between", value1, value2, "factnImporte");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoIsNull() {
            addCriterion("FACTV_FOLIONOTACREDITO is null");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoIsNotNull() {
            addCriterion("FACTV_FOLIONOTACREDITO is not null");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoEqualTo(String value) {
            addCriterion("FACTV_FOLIONOTACREDITO =", value, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoNotEqualTo(String value) {
            addCriterion("FACTV_FOLIONOTACREDITO <>", value, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoGreaterThan(String value) {
            addCriterion("FACTV_FOLIONOTACREDITO >", value, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_FOLIONOTACREDITO >=", value, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoLessThan(String value) {
            addCriterion("FACTV_FOLIONOTACREDITO <", value, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoLessThanOrEqualTo(String value) {
            addCriterion("FACTV_FOLIONOTACREDITO <=", value, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoLike(String value) {
            addCriterion("FACTV_FOLIONOTACREDITO like", value, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoNotLike(String value) {
            addCriterion("FACTV_FOLIONOTACREDITO not like", value, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoIn(List<String> values) {
            addCriterion("FACTV_FOLIONOTACREDITO in", values, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoNotIn(List<String> values) {
            addCriterion("FACTV_FOLIONOTACREDITO not in", values, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoBetween(String value1, String value2) {
            addCriterion("FACTV_FOLIONOTACREDITO between", value1, value2, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvFolionotacreditoNotBetween(String value1, String value2) {
            addCriterion("FACTV_FOLIONOTACREDITO not between", value1, value2, "factvFolionotacredito");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapIsNull() {
            addCriterion("FACTV_NOTACREDITOSAP is null");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapIsNotNull() {
            addCriterion("FACTV_NOTACREDITOSAP is not null");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapEqualTo(String value) {
            addCriterion("FACTV_NOTACREDITOSAP =", value, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapNotEqualTo(String value) {
            addCriterion("FACTV_NOTACREDITOSAP <>", value, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapGreaterThan(String value) {
            addCriterion("FACTV_NOTACREDITOSAP >", value, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_NOTACREDITOSAP >=", value, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapLessThan(String value) {
            addCriterion("FACTV_NOTACREDITOSAP <", value, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapLessThanOrEqualTo(String value) {
            addCriterion("FACTV_NOTACREDITOSAP <=", value, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapLike(String value) {
            addCriterion("FACTV_NOTACREDITOSAP like", value, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapNotLike(String value) {
            addCriterion("FACTV_NOTACREDITOSAP not like", value, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapIn(List<String> values) {
            addCriterion("FACTV_NOTACREDITOSAP in", values, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapNotIn(List<String> values) {
            addCriterion("FACTV_NOTACREDITOSAP not in", values, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapBetween(String value1, String value2) {
            addCriterion("FACTV_NOTACREDITOSAP between", value1, value2, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvNotacreditosapNotBetween(String value1, String value2) {
            addCriterion("FACTV_NOTACREDITOSAP not between", value1, value2, "factvNotacreditosap");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaIsNull() {
            addCriterion("FACTV_CLASEFACTURA is null");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaIsNotNull() {
            addCriterion("FACTV_CLASEFACTURA is not null");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaEqualTo(String value) {
            addCriterion("FACTV_CLASEFACTURA =", value, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaNotEqualTo(String value) {
            addCriterion("FACTV_CLASEFACTURA <>", value, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaGreaterThan(String value) {
            addCriterion("FACTV_CLASEFACTURA >", value, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_CLASEFACTURA >=", value, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaLessThan(String value) {
            addCriterion("FACTV_CLASEFACTURA <", value, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaLessThanOrEqualTo(String value) {
            addCriterion("FACTV_CLASEFACTURA <=", value, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaLike(String value) {
            addCriterion("FACTV_CLASEFACTURA like", value, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaNotLike(String value) {
            addCriterion("FACTV_CLASEFACTURA not like", value, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaIn(List<String> values) {
            addCriterion("FACTV_CLASEFACTURA in", values, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaNotIn(List<String> values) {
            addCriterion("FACTV_CLASEFACTURA not in", values, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaBetween(String value1, String value2) {
            addCriterion("FACTV_CLASEFACTURA between", value1, value2, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClasefacturaNotBetween(String value1, String value2) {
            addCriterion("FACTV_CLASEFACTURA not between", value1, value2, "factvClasefactura");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionIsNull() {
            addCriterion("FACTV_CLASEEXPEDICION is null");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionIsNotNull() {
            addCriterion("FACTV_CLASEEXPEDICION is not null");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionEqualTo(String value) {
            addCriterion("FACTV_CLASEEXPEDICION =", value, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionNotEqualTo(String value) {
            addCriterion("FACTV_CLASEEXPEDICION <>", value, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionGreaterThan(String value) {
            addCriterion("FACTV_CLASEEXPEDICION >", value, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_CLASEEXPEDICION >=", value, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionLessThan(String value) {
            addCriterion("FACTV_CLASEEXPEDICION <", value, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionLessThanOrEqualTo(String value) {
            addCriterion("FACTV_CLASEEXPEDICION <=", value, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionLike(String value) {
            addCriterion("FACTV_CLASEEXPEDICION like", value, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionNotLike(String value) {
            addCriterion("FACTV_CLASEEXPEDICION not like", value, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionIn(List<String> values) {
            addCriterion("FACTV_CLASEEXPEDICION in", values, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionNotIn(List<String> values) {
            addCriterion("FACTV_CLASEEXPEDICION not in", values, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionBetween(String value1, String value2) {
            addCriterion("FACTV_CLASEEXPEDICION between", value1, value2, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvClaseexpedicionNotBetween(String value1, String value2) {
            addCriterion("FACTV_CLASEEXPEDICION not between", value1, value2, "factvClaseexpedicion");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaIsNull() {
            addCriterion("FACTV_ESTADOFACTURA is null");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaIsNotNull() {
            addCriterion("FACTV_ESTADOFACTURA is not null");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaEqualTo(String value) {
            addCriterion("FACTV_ESTADOFACTURA =", value, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaNotEqualTo(String value) {
            addCriterion("FACTV_ESTADOFACTURA <>", value, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaGreaterThan(String value) {
            addCriterion("FACTV_ESTADOFACTURA >", value, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_ESTADOFACTURA >=", value, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaLessThan(String value) {
            addCriterion("FACTV_ESTADOFACTURA <", value, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaLessThanOrEqualTo(String value) {
            addCriterion("FACTV_ESTADOFACTURA <=", value, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaLike(String value) {
            addCriterion("FACTV_ESTADOFACTURA like", value, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaNotLike(String value) {
            addCriterion("FACTV_ESTADOFACTURA not like", value, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaIn(List<String> values) {
            addCriterion("FACTV_ESTADOFACTURA in", values, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaNotIn(List<String> values) {
            addCriterion("FACTV_ESTADOFACTURA not in", values, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaBetween(String value1, String value2) {
            addCriterion("FACTV_ESTADOFACTURA between", value1, value2, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvEstadofacturaNotBetween(String value1, String value2) {
            addCriterion("FACTV_ESTADOFACTURA not between", value1, value2, "factvEstadofactura");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaIsNull() {
            addCriterion("FACTV_ORGANIZACIONVENTA is null");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaIsNotNull() {
            addCriterion("FACTV_ORGANIZACIONVENTA is not null");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaEqualTo(String value) {
            addCriterion("FACTV_ORGANIZACIONVENTA =", value, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaNotEqualTo(String value) {
            addCriterion("FACTV_ORGANIZACIONVENTA <>", value, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaGreaterThan(String value) {
            addCriterion("FACTV_ORGANIZACIONVENTA >", value, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_ORGANIZACIONVENTA >=", value, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaLessThan(String value) {
            addCriterion("FACTV_ORGANIZACIONVENTA <", value, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaLessThanOrEqualTo(String value) {
            addCriterion("FACTV_ORGANIZACIONVENTA <=", value, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaLike(String value) {
            addCriterion("FACTV_ORGANIZACIONVENTA like", value, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaNotLike(String value) {
            addCriterion("FACTV_ORGANIZACIONVENTA not like", value, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaIn(List<String> values) {
            addCriterion("FACTV_ORGANIZACIONVENTA in", values, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaNotIn(List<String> values) {
            addCriterion("FACTV_ORGANIZACIONVENTA not in", values, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaBetween(String value1, String value2) {
            addCriterion("FACTV_ORGANIZACIONVENTA between", value1, value2, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvOrganizacionventaNotBetween(String value1, String value2) {
            addCriterion("FACTV_ORGANIZACIONVENTA not between", value1, value2, "factvOrganizacionventa");
            return (Criteria) this;
        }

        public Criteria andFactvCanalIsNull() {
            addCriterion("FACTV_CANAL is null");
            return (Criteria) this;
        }

        public Criteria andFactvCanalIsNotNull() {
            addCriterion("FACTV_CANAL is not null");
            return (Criteria) this;
        }

        public Criteria andFactvCanalEqualTo(String value) {
            addCriterion("FACTV_CANAL =", value, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalNotEqualTo(String value) {
            addCriterion("FACTV_CANAL <>", value, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalGreaterThan(String value) {
            addCriterion("FACTV_CANAL >", value, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_CANAL >=", value, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalLessThan(String value) {
            addCriterion("FACTV_CANAL <", value, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalLessThanOrEqualTo(String value) {
            addCriterion("FACTV_CANAL <=", value, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalLike(String value) {
            addCriterion("FACTV_CANAL like", value, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalNotLike(String value) {
            addCriterion("FACTV_CANAL not like", value, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalIn(List<String> values) {
            addCriterion("FACTV_CANAL in", values, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalNotIn(List<String> values) {
            addCriterion("FACTV_CANAL not in", values, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalBetween(String value1, String value2) {
            addCriterion("FACTV_CANAL between", value1, value2, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactvCanalNotBetween(String value1, String value2) {
            addCriterion("FACTV_CANAL not between", value1, value2, "factvCanal");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaIsNull() {
            addCriterion("FACTD_FECHASALIDA is null");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaIsNotNull() {
            addCriterion("FACTD_FECHASALIDA is not null");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaEqualTo(Date value) {
            addCriterion("FACTD_FECHASALIDA =", value, "factdFechasalida");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaNotEqualTo(Date value) {
            addCriterion("FACTD_FECHASALIDA <>", value, "factdFechasalida");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaGreaterThan(Date value) {
            addCriterion("FACTD_FECHASALIDA >", value, "factdFechasalida");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaGreaterThanOrEqualTo(Date value) {
            addCriterion("FACTD_FECHASALIDA >=", value, "factdFechasalida");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaLessThan(Date value) {
            addCriterion("FACTD_FECHASALIDA <", value, "factdFechasalida");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaLessThanOrEqualTo(Date value) {
            addCriterion("FACTD_FECHASALIDA <=", value, "factdFechasalida");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaIn(List<Date> values) {
            addCriterion("FACTD_FECHASALIDA in", values, "factdFechasalida");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaNotIn(List<Date> values) {
            addCriterion("FACTD_FECHASALIDA not in", values, "factdFechasalida");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaBetween(Date value1, Date value2) {
            addCriterion("FACTD_FECHASALIDA between", value1, value2, "factdFechasalida");
            return (Criteria) this;
        }

        public Criteria andFactdFechasalidaNotBetween(Date value1, Date value2) {
            addCriterion("FACTD_FECHASALIDA not between", value1, value2, "factdFechasalida");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaIsNull() {
            addCriterion("FACTV_FACTURA is null");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaIsNotNull() {
            addCriterion("FACTV_FACTURA is not null");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaEqualTo(String value) {
            addCriterion("FACTV_FACTURA =", value, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaNotEqualTo(String value) {
            addCriterion("FACTV_FACTURA <>", value, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaGreaterThan(String value) {
            addCriterion("FACTV_FACTURA >", value, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_FACTURA >=", value, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaLessThan(String value) {
            addCriterion("FACTV_FACTURA <", value, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaLessThanOrEqualTo(String value) {
            addCriterion("FACTV_FACTURA <=", value, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaLike(String value) {
            addCriterion("FACTV_FACTURA like", value, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaNotLike(String value) {
            addCriterion("FACTV_FACTURA not like", value, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaIn(List<String> values) {
            addCriterion("FACTV_FACTURA in", values, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaNotIn(List<String> values) {
            addCriterion("FACTV_FACTURA not in", values, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaBetween(String value1, String value2) {
            addCriterion("FACTV_FACTURA between", value1, value2, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvFacturaNotBetween(String value1, String value2) {
            addCriterion("FACTV_FACTURA not between", value1, value2, "factvFactura");
            return (Criteria) this;
        }

        public Criteria andFactvSerieIsNull() {
            addCriterion("FACTV_SERIE is null");
            return (Criteria) this;
        }

        public Criteria andFactvSerieIsNotNull() {
            addCriterion("FACTV_SERIE is not null");
            return (Criteria) this;
        }

        public Criteria andFactvSerieEqualTo(String value) {
            addCriterion("FACTV_SERIE =", value, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieNotEqualTo(String value) {
            addCriterion("FACTV_SERIE <>", value, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieGreaterThan(String value) {
            addCriterion("FACTV_SERIE >", value, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_SERIE >=", value, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieLessThan(String value) {
            addCriterion("FACTV_SERIE <", value, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieLessThanOrEqualTo(String value) {
            addCriterion("FACTV_SERIE <=", value, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieLike(String value) {
            addCriterion("FACTV_SERIE like", value, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieNotLike(String value) {
            addCriterion("FACTV_SERIE not like", value, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieIn(List<String> values) {
            addCriterion("FACTV_SERIE in", values, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieNotIn(List<String> values) {
            addCriterion("FACTV_SERIE not in", values, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieBetween(String value1, String value2) {
            addCriterion("FACTV_SERIE between", value1, value2, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSerieNotBetween(String value1, String value2) {
            addCriterion("FACTV_SERIE not between", value1, value2, "factvSerie");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoIsNull() {
            addCriterion("FACTV_SERIECODIGO is null");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoIsNotNull() {
            addCriterion("FACTV_SERIECODIGO is not null");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoEqualTo(String value) {
            addCriterion("FACTV_SERIECODIGO =", value, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoNotEqualTo(String value) {
            addCriterion("FACTV_SERIECODIGO <>", value, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoGreaterThan(String value) {
            addCriterion("FACTV_SERIECODIGO >", value, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_SERIECODIGO >=", value, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoLessThan(String value) {
            addCriterion("FACTV_SERIECODIGO <", value, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoLessThanOrEqualTo(String value) {
            addCriterion("FACTV_SERIECODIGO <=", value, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoLike(String value) {
            addCriterion("FACTV_SERIECODIGO like", value, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoNotLike(String value) {
            addCriterion("FACTV_SERIECODIGO not like", value, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoIn(List<String> values) {
            addCriterion("FACTV_SERIECODIGO in", values, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoNotIn(List<String> values) {
            addCriterion("FACTV_SERIECODIGO not in", values, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoBetween(String value1, String value2) {
            addCriterion("FACTV_SERIECODIGO between", value1, value2, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvSeriecodigoNotBetween(String value1, String value2) {
            addCriterion("FACTV_SERIECODIGO not between", value1, value2, "factvSeriecodigo");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionIsNull() {
            addCriterion("FACTV_USUARIOCREACION is null");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionIsNotNull() {
            addCriterion("FACTV_USUARIOCREACION is not null");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionEqualTo(String value) {
            addCriterion("FACTV_USUARIOCREACION =", value, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionNotEqualTo(String value) {
            addCriterion("FACTV_USUARIOCREACION <>", value, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionGreaterThan(String value) {
            addCriterion("FACTV_USUARIOCREACION >", value, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_USUARIOCREACION >=", value, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionLessThan(String value) {
            addCriterion("FACTV_USUARIOCREACION <", value, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionLessThanOrEqualTo(String value) {
            addCriterion("FACTV_USUARIOCREACION <=", value, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionLike(String value) {
            addCriterion("FACTV_USUARIOCREACION like", value, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionNotLike(String value) {
            addCriterion("FACTV_USUARIOCREACION not like", value, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionIn(List<String> values) {
            addCriterion("FACTV_USUARIOCREACION in", values, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionNotIn(List<String> values) {
            addCriterion("FACTV_USUARIOCREACION not in", values, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionBetween(String value1, String value2) {
            addCriterion("FACTV_USUARIOCREACION between", value1, value2, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariocreacionNotBetween(String value1, String value2) {
            addCriterion("FACTV_USUARIOCREACION not between", value1, value2, "factvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionIsNull() {
            addCriterion("FACTD_FECHACREACION is null");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionIsNotNull() {
            addCriterion("FACTD_FECHACREACION is not null");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionEqualTo(Date value) {
            addCriterion("FACTD_FECHACREACION =", value, "factdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionNotEqualTo(Date value) {
            addCriterion("FACTD_FECHACREACION <>", value, "factdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionGreaterThan(Date value) {
            addCriterion("FACTD_FECHACREACION >", value, "factdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionGreaterThanOrEqualTo(Date value) {
            addCriterion("FACTD_FECHACREACION >=", value, "factdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionLessThan(Date value) {
            addCriterion("FACTD_FECHACREACION <", value, "factdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionLessThanOrEqualTo(Date value) {
            addCriterion("FACTD_FECHACREACION <=", value, "factdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionIn(List<Date> values) {
            addCriterion("FACTD_FECHACREACION in", values, "factdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionNotIn(List<Date> values) {
            addCriterion("FACTD_FECHACREACION not in", values, "factdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionBetween(Date value1, Date value2) {
            addCriterion("FACTD_FECHACREACION between", value1, value2, "factdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechacreacionNotBetween(Date value1, Date value2) {
            addCriterion("FACTD_FECHACREACION not between", value1, value2, "factdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionIsNull() {
            addCriterion("FACTV_USUARIOMODIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionIsNotNull() {
            addCriterion("FACTV_USUARIOMODIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionEqualTo(String value) {
            addCriterion("FACTV_USUARIOMODIFICACION =", value, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionNotEqualTo(String value) {
            addCriterion("FACTV_USUARIOMODIFICACION <>", value, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionGreaterThan(String value) {
            addCriterion("FACTV_USUARIOMODIFICACION >", value, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionGreaterThanOrEqualTo(String value) {
            addCriterion("FACTV_USUARIOMODIFICACION >=", value, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionLessThan(String value) {
            addCriterion("FACTV_USUARIOMODIFICACION <", value, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionLessThanOrEqualTo(String value) {
            addCriterion("FACTV_USUARIOMODIFICACION <=", value, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionLike(String value) {
            addCriterion("FACTV_USUARIOMODIFICACION like", value, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionNotLike(String value) {
            addCriterion("FACTV_USUARIOMODIFICACION not like", value, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionIn(List<String> values) {
            addCriterion("FACTV_USUARIOMODIFICACION in", values, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionNotIn(List<String> values) {
            addCriterion("FACTV_USUARIOMODIFICACION not in", values, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionBetween(String value1, String value2) {
            addCriterion("FACTV_USUARIOMODIFICACION between", value1, value2, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactvUsuariomodificacionNotBetween(String value1, String value2) {
            addCriterion("FACTV_USUARIOMODIFICACION not between", value1, value2, "factvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionIsNull() {
            addCriterion("FACTD_FECHAMODIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionIsNotNull() {
            addCriterion("FACTD_FECHAMODIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionEqualTo(Date value) {
            addCriterion("FACTD_FECHAMODIFICACION =", value, "factdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionNotEqualTo(Date value) {
            addCriterion("FACTD_FECHAMODIFICACION <>", value, "factdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionGreaterThan(Date value) {
            addCriterion("FACTD_FECHAMODIFICACION >", value, "factdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionGreaterThanOrEqualTo(Date value) {
            addCriterion("FACTD_FECHAMODIFICACION >=", value, "factdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionLessThan(Date value) {
            addCriterion("FACTD_FECHAMODIFICACION <", value, "factdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionLessThanOrEqualTo(Date value) {
            addCriterion("FACTD_FECHAMODIFICACION <=", value, "factdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionIn(List<Date> values) {
            addCriterion("FACTD_FECHAMODIFICACION in", values, "factdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionNotIn(List<Date> values) {
            addCriterion("FACTD_FECHAMODIFICACION not in", values, "factdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionBetween(Date value1, Date value2) {
            addCriterion("FACTD_FECHAMODIFICACION between", value1, value2, "factdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andFactdFechamodificacionNotBetween(Date value1, Date value2) {
            addCriterion("FACTD_FECHAMODIFICACION not between", value1, value2, "factdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoIsNull() {
            addCriterion("FACTN_ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoIsNotNull() {
            addCriterion("FACTN_ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoEqualTo(Short value) {
            addCriterion("FACTN_ESTADO =", value, "factnEstado");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoNotEqualTo(Short value) {
            addCriterion("FACTN_ESTADO <>", value, "factnEstado");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoGreaterThan(Short value) {
            addCriterion("FACTN_ESTADO >", value, "factnEstado");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoGreaterThanOrEqualTo(Short value) {
            addCriterion("FACTN_ESTADO >=", value, "factnEstado");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoLessThan(Short value) {
            addCriterion("FACTN_ESTADO <", value, "factnEstado");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoLessThanOrEqualTo(Short value) {
            addCriterion("FACTN_ESTADO <=", value, "factnEstado");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoIn(List<Short> values) {
            addCriterion("FACTN_ESTADO in", values, "factnEstado");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoNotIn(List<Short> values) {
            addCriterion("FACTN_ESTADO not in", values, "factnEstado");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoBetween(Short value1, Short value2) {
            addCriterion("FACTN_ESTADO between", value1, value2, "factnEstado");
            return (Criteria) this;
        }

        public Criteria andFactnEstadoNotBetween(Short value1, Short value2) {
            addCriterion("FACTN_ESTADO not between", value1, value2, "factnEstado");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}