package com.caasa.comexsap.exportaciones.model.domain;

import java.math.BigDecimal;
import java.util.Date;

public class ComexstExportacionpedido {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_ID
     *
     * @mbg.generated
     */
    private Integer epednId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDEXPORTACION
     *
     * @mbg.generated
     */
    private Integer epednIdexportacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_PEDIDOPCP
     *
     * @mbg.generated
     */
    private String epedvPedidopcp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDAD
     *
     * @mbg.generated
     */
    private Integer epednCantidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IMPORTE
     *
     * @mbg.generated
     */
    private BigDecimal epednImporte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_PEDIDOSAP
     *
     * @mbg.generated
     */
    private String epedvPedidosap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDPOSICION
     *
     * @mbg.generated
     */
    private Integer epednIdposicion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_FOLIO
     *
     * @mbg.generated
     */
    private String epedvFolio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDPARTIDAARANCELARIA
     *
     * @mbg.generated
     */
    private Integer epednIdpartidaarancelaria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_DESCRIPCIONCOMERCIAL
     *
     * @mbg.generated
     */
    private String epedvDescripcioncomercial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHADISPONIBILIDAD
     *
     * @mbg.generated
     */
    private Date epeddFechadisponibilidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDA
     *
     * @mbg.generated
     */
    private Integer epednIdunidadmedida;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDAVENTA
     *
     * @mbg.generated
     */
    private Integer epednIdunidadmedidaventa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDADVENTA
     *
     * @mbg.generated
     */
    private BigDecimal epednCantidadventa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDACONVERSION
     *
     * @mbg.generated
     */
    private Integer epednIdunidadmedidaconversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDADCONVERSION
     *
     * @mbg.generated
     */
    private BigDecimal epednCantidadconversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_PRECIOUNITARIOCONVERSION
     *
     * @mbg.generated
     */
    private BigDecimal epednPreciounitarioconversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_ITEMSAP
     *
     * @mbg.generated
     */
    private Integer epednItemsap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDALMACEN
     *
     * @mbg.generated
     */
    private Integer epednIdalmacen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_PESOTONELADA
     *
     * @mbg.generated
     */
    private BigDecimal epednPesotonelada;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_PRECIOUNITARIO
     *
     * @mbg.generated
     */
    private BigDecimal epednPreciounitario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDMONEDA
     *
     * @mbg.generated
     */
    private Integer epednIdmoneda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_MENSAJESAP
     *
     * @mbg.generated
     */
    private String epedvMensajesap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_ENTREGA
     *
     * @mbg.generated
     */
    private String epedvEntrega;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_BLOQUEO
     *
     * @mbg.generated
     */
    private String epedvBloqueo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_REFERENCIA
     *
     * @mbg.generated
     */
    private String epedvReferencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_COMPONENTETEXTO
     *
     * @mbg.generated
     */
    private String epedvComponentetexto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_USUARIOCREACION
     *
     * @mbg.generated
     */
    private String epedvUsuariocreacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHACREACION
     *
     * @mbg.generated
     */
    private Date epeddFechacreacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_USUARIOMODIFICACION
     *
     * @mbg.generated
     */
    private String epedvUsuariomodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHAMODIFICACION
     *
     * @mbg.generated
     */
    private Date epeddFechamodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_ESTADO
     *
     * @mbg.generated
     */
    private Short epednEstado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_CODIGOSAP
     *
     * @mbg.generated
     */
    private String epedvCodigosap;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_ID
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_ID
     *
     * @mbg.generated
     */
    public Integer getEpednId() {
        return epednId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_ID
     *
     * @param epednId the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_ID
     *
     * @mbg.generated
     */
    public void setEpednId(Integer epednId) {
        this.epednId = epednId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDEXPORTACION
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_IDEXPORTACION
     *
     * @mbg.generated
     */
    public Integer getEpednIdexportacion() {
        return epednIdexportacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDEXPORTACION
     *
     * @param epednIdexportacion the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_IDEXPORTACION
     *
     * @mbg.generated
     */
    public void setEpednIdexportacion(Integer epednIdexportacion) {
        this.epednIdexportacion = epednIdexportacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_PEDIDOPCP
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_PEDIDOPCP
     *
     * @mbg.generated
     */
    public String getEpedvPedidopcp() {
        return epedvPedidopcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_PEDIDOPCP
     *
     * @param epedvPedidopcp the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_PEDIDOPCP
     *
     * @mbg.generated
     */
    public void setEpedvPedidopcp(String epedvPedidopcp) {
        this.epedvPedidopcp = epedvPedidopcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDAD
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDAD
     *
     * @mbg.generated
     */
    public Integer getEpednCantidad() {
        return epednCantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDAD
     *
     * @param epednCantidad the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDAD
     *
     * @mbg.generated
     */
    public void setEpednCantidad(Integer epednCantidad) {
        this.epednCantidad = epednCantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IMPORTE
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_IMPORTE
     *
     * @mbg.generated
     */
    public BigDecimal getEpednImporte() {
        return epednImporte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IMPORTE
     *
     * @param epednImporte the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_IMPORTE
     *
     * @mbg.generated
     */
    public void setEpednImporte(BigDecimal epednImporte) {
        this.epednImporte = epednImporte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_PEDIDOSAP
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_PEDIDOSAP
     *
     * @mbg.generated
     */
    public String getEpedvPedidosap() {
        return epedvPedidosap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_PEDIDOSAP
     *
     * @param epedvPedidosap the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_PEDIDOSAP
     *
     * @mbg.generated
     */
    public void setEpedvPedidosap(String epedvPedidosap) {
        this.epedvPedidosap = epedvPedidosap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDPOSICION
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_IDPOSICION
     *
     * @mbg.generated
     */
    public Integer getEpednIdposicion() {
        return epednIdposicion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDPOSICION
     *
     * @param epednIdposicion the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_IDPOSICION
     *
     * @mbg.generated
     */
    public void setEpednIdposicion(Integer epednIdposicion) {
        this.epednIdposicion = epednIdposicion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_FOLIO
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_FOLIO
     *
     * @mbg.generated
     */
    public String getEpedvFolio() {
        return epedvFolio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_FOLIO
     *
     * @param epedvFolio the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_FOLIO
     *
     * @mbg.generated
     */
    public void setEpedvFolio(String epedvFolio) {
        this.epedvFolio = epedvFolio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDPARTIDAARANCELARIA
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_IDPARTIDAARANCELARIA
     *
     * @mbg.generated
     */
    public Integer getEpednIdpartidaarancelaria() {
        return epednIdpartidaarancelaria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDPARTIDAARANCELARIA
     *
     * @param epednIdpartidaarancelaria the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_IDPARTIDAARANCELARIA
     *
     * @mbg.generated
     */
    public void setEpednIdpartidaarancelaria(Integer epednIdpartidaarancelaria) {
        this.epednIdpartidaarancelaria = epednIdpartidaarancelaria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_DESCRIPCIONCOMERCIAL
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_DESCRIPCIONCOMERCIAL
     *
     * @mbg.generated
     */
    public String getEpedvDescripcioncomercial() {
        return epedvDescripcioncomercial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_DESCRIPCIONCOMERCIAL
     *
     * @param epedvDescripcioncomercial the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_DESCRIPCIONCOMERCIAL
     *
     * @mbg.generated
     */
    public void setEpedvDescripcioncomercial(String epedvDescripcioncomercial) {
        this.epedvDescripcioncomercial = epedvDescripcioncomercial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHADISPONIBILIDAD
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHADISPONIBILIDAD
     *
     * @mbg.generated
     */
    public Date getEpeddFechadisponibilidad() {
        return epeddFechadisponibilidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHADISPONIBILIDAD
     *
     * @param epeddFechadisponibilidad the value for COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHADISPONIBILIDAD
     *
     * @mbg.generated
     */
    public void setEpeddFechadisponibilidad(Date epeddFechadisponibilidad) {
        this.epeddFechadisponibilidad = epeddFechadisponibilidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDA
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDA
     *
     * @mbg.generated
     */
    public Integer getEpednIdunidadmedida() {
        return epednIdunidadmedida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDA
     *
     * @param epednIdunidadmedida the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDA
     *
     * @mbg.generated
     */
    public void setEpednIdunidadmedida(Integer epednIdunidadmedida) {
        this.epednIdunidadmedida = epednIdunidadmedida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDAVENTA
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDAVENTA
     *
     * @mbg.generated
     */
    public Integer getEpednIdunidadmedidaventa() {
        return epednIdunidadmedidaventa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDAVENTA
     *
     * @param epednIdunidadmedidaventa the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDAVENTA
     *
     * @mbg.generated
     */
    public void setEpednIdunidadmedidaventa(Integer epednIdunidadmedidaventa) {
        this.epednIdunidadmedidaventa = epednIdunidadmedidaventa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDADVENTA
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDADVENTA
     *
     * @mbg.generated
     */
    public BigDecimal getEpednCantidadventa() {
        return epednCantidadventa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDADVENTA
     *
     * @param epednCantidadventa the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDADVENTA
     *
     * @mbg.generated
     */
    public void setEpednCantidadventa(BigDecimal epednCantidadventa) {
        this.epednCantidadventa = epednCantidadventa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDACONVERSION
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDACONVERSION
     *
     * @mbg.generated
     */
    public Integer getEpednIdunidadmedidaconversion() {
        return epednIdunidadmedidaconversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDACONVERSION
     *
     * @param epednIdunidadmedidaconversion the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_IDUNIDADMEDIDACONVERSION
     *
     * @mbg.generated
     */
    public void setEpednIdunidadmedidaconversion(Integer epednIdunidadmedidaconversion) {
        this.epednIdunidadmedidaconversion = epednIdunidadmedidaconversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDADCONVERSION
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDADCONVERSION
     *
     * @mbg.generated
     */
    public BigDecimal getEpednCantidadconversion() {
        return epednCantidadconversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDADCONVERSION
     *
     * @param epednCantidadconversion the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_CANTIDADCONVERSION
     *
     * @mbg.generated
     */
    public void setEpednCantidadconversion(BigDecimal epednCantidadconversion) {
        this.epednCantidadconversion = epednCantidadconversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_PRECIOUNITARIOCONVERSION
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_PRECIOUNITARIOCONVERSION
     *
     * @mbg.generated
     */
    public BigDecimal getEpednPreciounitarioconversion() {
        return epednPreciounitarioconversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_PRECIOUNITARIOCONVERSION
     *
     * @param epednPreciounitarioconversion the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_PRECIOUNITARIOCONVERSION
     *
     * @mbg.generated
     */
    public void setEpednPreciounitarioconversion(BigDecimal epednPreciounitarioconversion) {
        this.epednPreciounitarioconversion = epednPreciounitarioconversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_ITEMSAP
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_ITEMSAP
     *
     * @mbg.generated
     */
    public Integer getEpednItemsap() {
        return epednItemsap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_ITEMSAP
     *
     * @param epednItemsap the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_ITEMSAP
     *
     * @mbg.generated
     */
    public void setEpednItemsap(Integer epednItemsap) {
        this.epednItemsap = epednItemsap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDALMACEN
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_IDALMACEN
     *
     * @mbg.generated
     */
    public Integer getEpednIdalmacen() {
        return epednIdalmacen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDALMACEN
     *
     * @param epednIdalmacen the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_IDALMACEN
     *
     * @mbg.generated
     */
    public void setEpednIdalmacen(Integer epednIdalmacen) {
        this.epednIdalmacen = epednIdalmacen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_PESOTONELADA
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_PESOTONELADA
     *
     * @mbg.generated
     */
    public BigDecimal getEpednPesotonelada() {
        return epednPesotonelada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_PESOTONELADA
     *
     * @param epednPesotonelada the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_PESOTONELADA
     *
     * @mbg.generated
     */
    public void setEpednPesotonelada(BigDecimal epednPesotonelada) {
        this.epednPesotonelada = epednPesotonelada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_PRECIOUNITARIO
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_PRECIOUNITARIO
     *
     * @mbg.generated
     */
    public BigDecimal getEpednPreciounitario() {
        return epednPreciounitario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_PRECIOUNITARIO
     *
     * @param epednPreciounitario the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_PRECIOUNITARIO
     *
     * @mbg.generated
     */
    public void setEpednPreciounitario(BigDecimal epednPreciounitario) {
        this.epednPreciounitario = epednPreciounitario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDMONEDA
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_IDMONEDA
     *
     * @mbg.generated
     */
    public Integer getEpednIdmoneda() {
        return epednIdmoneda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_IDMONEDA
     *
     * @param epednIdmoneda the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_IDMONEDA
     *
     * @mbg.generated
     */
    public void setEpednIdmoneda(Integer epednIdmoneda) {
        this.epednIdmoneda = epednIdmoneda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_MENSAJESAP
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_MENSAJESAP
     *
     * @mbg.generated
     */
    public String getEpedvMensajesap() {
        return epedvMensajesap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_MENSAJESAP
     *
     * @param epedvMensajesap the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_MENSAJESAP
     *
     * @mbg.generated
     */
    public void setEpedvMensajesap(String epedvMensajesap) {
        this.epedvMensajesap = epedvMensajesap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_ENTREGA
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_ENTREGA
     *
     * @mbg.generated
     */
    public String getEpedvEntrega() {
        return epedvEntrega;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_ENTREGA
     *
     * @param epedvEntrega the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_ENTREGA
     *
     * @mbg.generated
     */
    public void setEpedvEntrega(String epedvEntrega) {
        this.epedvEntrega = epedvEntrega;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_BLOQUEO
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_BLOQUEO
     *
     * @mbg.generated
     */
    public String getEpedvBloqueo() {
        return epedvBloqueo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_BLOQUEO
     *
     * @param epedvBloqueo the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_BLOQUEO
     *
     * @mbg.generated
     */
    public void setEpedvBloqueo(String epedvBloqueo) {
        this.epedvBloqueo = epedvBloqueo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_REFERENCIA
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_REFERENCIA
     *
     * @mbg.generated
     */
    public String getEpedvReferencia() {
        return epedvReferencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_REFERENCIA
     *
     * @param epedvReferencia the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_REFERENCIA
     *
     * @mbg.generated
     */
    public void setEpedvReferencia(String epedvReferencia) {
        this.epedvReferencia = epedvReferencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_COMPONENTETEXTO
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_COMPONENTETEXTO
     *
     * @mbg.generated
     */
    public String getEpedvComponentetexto() {
        return epedvComponentetexto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_COMPONENTETEXTO
     *
     * @param epedvComponentetexto the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_COMPONENTETEXTO
     *
     * @mbg.generated
     */
    public void setEpedvComponentetexto(String epedvComponentetexto) {
        this.epedvComponentetexto = epedvComponentetexto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_USUARIOCREACION
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_USUARIOCREACION
     *
     * @mbg.generated
     */
    public String getEpedvUsuariocreacion() {
        return epedvUsuariocreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_USUARIOCREACION
     *
     * @param epedvUsuariocreacion the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_USUARIOCREACION
     *
     * @mbg.generated
     */
    public void setEpedvUsuariocreacion(String epedvUsuariocreacion) {
        this.epedvUsuariocreacion = epedvUsuariocreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHACREACION
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHACREACION
     *
     * @mbg.generated
     */
    public Date getEpeddFechacreacion() {
        return epeddFechacreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHACREACION
     *
     * @param epeddFechacreacion the value for COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHACREACION
     *
     * @mbg.generated
     */
    public void setEpeddFechacreacion(Date epeddFechacreacion) {
        this.epeddFechacreacion = epeddFechacreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_USUARIOMODIFICACION
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_USUARIOMODIFICACION
     *
     * @mbg.generated
     */
    public String getEpedvUsuariomodificacion() {
        return epedvUsuariomodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_USUARIOMODIFICACION
     *
     * @param epedvUsuariomodificacion the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_USUARIOMODIFICACION
     *
     * @mbg.generated
     */
    public void setEpedvUsuariomodificacion(String epedvUsuariomodificacion) {
        this.epedvUsuariomodificacion = epedvUsuariomodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHAMODIFICACION
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHAMODIFICACION
     *
     * @mbg.generated
     */
    public Date getEpeddFechamodificacion() {
        return epeddFechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHAMODIFICACION
     *
     * @param epeddFechamodificacion the value for COMEXST_EXPORTACIONPEDIDO.EPEDD_FECHAMODIFICACION
     *
     * @mbg.generated
     */
    public void setEpeddFechamodificacion(Date epeddFechamodificacion) {
        this.epeddFechamodificacion = epeddFechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_ESTADO
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDN_ESTADO
     *
     * @mbg.generated
     */
    public Short getEpednEstado() {
        return epednEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDN_ESTADO
     *
     * @param epednEstado the value for COMEXST_EXPORTACIONPEDIDO.EPEDN_ESTADO
     *
     * @mbg.generated
     */
    public void setEpednEstado(Short epednEstado) {
        this.epednEstado = epednEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_CODIGOSAP
     *
     * @return the value of COMEXST_EXPORTACIONPEDIDO.EPEDV_CODIGOSAP
     *
     * @mbg.generated
     */
    public String getEpedvCodigosap() {
        return epedvCodigosap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_EXPORTACIONPEDIDO.EPEDV_CODIGOSAP
     *
     * @param epedvCodigosap the value for COMEXST_EXPORTACIONPEDIDO.EPEDV_CODIGOSAP
     *
     * @mbg.generated
     */
    public void setEpedvCodigosap(String epedvCodigosap) {
        this.epedvCodigosap = epedvCodigosap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", epednId=").append(epednId);
        sb.append(", epednIdexportacion=").append(epednIdexportacion);
        sb.append(", epedvPedidopcp=").append(epedvPedidopcp);
        sb.append(", epednCantidad=").append(epednCantidad);
        sb.append(", epednImporte=").append(epednImporte);
        sb.append(", epedvPedidosap=").append(epedvPedidosap);
        sb.append(", epednIdposicion=").append(epednIdposicion);
        sb.append(", epedvFolio=").append(epedvFolio);
        sb.append(", epednIdpartidaarancelaria=").append(epednIdpartidaarancelaria);
        sb.append(", epedvDescripcioncomercial=").append(epedvDescripcioncomercial);
        sb.append(", epeddFechadisponibilidad=").append(epeddFechadisponibilidad);
        sb.append(", epednIdunidadmedida=").append(epednIdunidadmedida);
        sb.append(", epednIdunidadmedidaventa=").append(epednIdunidadmedidaventa);
        sb.append(", epednCantidadventa=").append(epednCantidadventa);
        sb.append(", epednIdunidadmedidaconversion=").append(epednIdunidadmedidaconversion);
        sb.append(", epednCantidadconversion=").append(epednCantidadconversion);
        sb.append(", epednPreciounitarioconversion=").append(epednPreciounitarioconversion);
        sb.append(", epednItemsap=").append(epednItemsap);
        sb.append(", epednIdalmacen=").append(epednIdalmacen);
        sb.append(", epednPesotonelada=").append(epednPesotonelada);
        sb.append(", epednPreciounitario=").append(epednPreciounitario);
        sb.append(", epednIdmoneda=").append(epednIdmoneda);
        sb.append(", epedvMensajesap=").append(epedvMensajesap);
        sb.append(", epedvEntrega=").append(epedvEntrega);
        sb.append(", epedvBloqueo=").append(epedvBloqueo);
        sb.append(", epedvReferencia=").append(epedvReferencia);
        sb.append(", epedvComponentetexto=").append(epedvComponentetexto);
        sb.append(", epedvUsuariocreacion=").append(epedvUsuariocreacion);
        sb.append(", epeddFechacreacion=").append(epeddFechacreacion);
        sb.append(", epedvUsuariomodificacion=").append(epedvUsuariomodificacion);
        sb.append(", epeddFechamodificacion=").append(epeddFechamodificacion);
        sb.append(", epednEstado=").append(epednEstado);
        sb.append(", epedvCodigosap=").append(epedvCodigosap);
        sb.append("]");
        return sb.toString();
    }
}