package com.caasa.comexsap.exportaciones.model.domain;

import java.util.Date;

public class ComexstClienteNuevo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE_NUEVO.CLIEN_ID
     *
     * @mbg.generated
     */
    private Integer clienId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE_NUEVO.CLIEV_CODIGOSAP
     *
     * @mbg.generated
     */
    private String clievCodigosap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE_NUEVO.CLIEV_NOMBRE
     *
     * @mbg.generated
     */
    private String clievNombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE_NUEVO.CLIEV_USUARIOCREACION
     *
     * @mbg.generated
     */
    private String clievUsuariocreacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE_NUEVO.CLIED_FECHACREACION
     *
     * @mbg.generated
     */
    private Date cliedFechacreacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE_NUEVO.CLIEV_USUARIOMODIFICACION
     *
     * @mbg.generated
     */
    private String clievUsuariomodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE_NUEVO.CLIED_FECHAMODIFICACION
     *
     * @mbg.generated
     */
    private Date cliedFechamodificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMEXST_CLIENTE_NUEVO.CLIEN_ESTADO
     *
     * @mbg.generated
     */
    private Short clienEstado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE_NUEVO.CLIEN_ID
     *
     * @return the value of COMEXST_CLIENTE_NUEVO.CLIEN_ID
     *
     * @mbg.generated
     */
    public Integer getClienId() {
        return clienId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE_NUEVO.CLIEN_ID
     *
     * @param clienId the value for COMEXST_CLIENTE_NUEVO.CLIEN_ID
     *
     * @mbg.generated
     */
    public void setClienId(Integer clienId) {
        this.clienId = clienId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE_NUEVO.CLIEV_CODIGOSAP
     *
     * @return the value of COMEXST_CLIENTE_NUEVO.CLIEV_CODIGOSAP
     *
     * @mbg.generated
     */
    public String getClievCodigosap() {
        return clievCodigosap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE_NUEVO.CLIEV_CODIGOSAP
     *
     * @param clievCodigosap the value for COMEXST_CLIENTE_NUEVO.CLIEV_CODIGOSAP
     *
     * @mbg.generated
     */
    public void setClievCodigosap(String clievCodigosap) {
        this.clievCodigosap = clievCodigosap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE_NUEVO.CLIEV_NOMBRE
     *
     * @return the value of COMEXST_CLIENTE_NUEVO.CLIEV_NOMBRE
     *
     * @mbg.generated
     */
    public String getClievNombre() {
        return clievNombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE_NUEVO.CLIEV_NOMBRE
     *
     * @param clievNombre the value for COMEXST_CLIENTE_NUEVO.CLIEV_NOMBRE
     *
     * @mbg.generated
     */
    public void setClievNombre(String clievNombre) {
        this.clievNombre = clievNombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE_NUEVO.CLIEV_USUARIOCREACION
     *
     * @return the value of COMEXST_CLIENTE_NUEVO.CLIEV_USUARIOCREACION
     *
     * @mbg.generated
     */
    public String getClievUsuariocreacion() {
        return clievUsuariocreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE_NUEVO.CLIEV_USUARIOCREACION
     *
     * @param clievUsuariocreacion the value for COMEXST_CLIENTE_NUEVO.CLIEV_USUARIOCREACION
     *
     * @mbg.generated
     */
    public void setClievUsuariocreacion(String clievUsuariocreacion) {
        this.clievUsuariocreacion = clievUsuariocreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE_NUEVO.CLIED_FECHACREACION
     *
     * @return the value of COMEXST_CLIENTE_NUEVO.CLIED_FECHACREACION
     *
     * @mbg.generated
     */
    public Date getCliedFechacreacion() {
        return cliedFechacreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE_NUEVO.CLIED_FECHACREACION
     *
     * @param cliedFechacreacion the value for COMEXST_CLIENTE_NUEVO.CLIED_FECHACREACION
     *
     * @mbg.generated
     */
    public void setCliedFechacreacion(Date cliedFechacreacion) {
        this.cliedFechacreacion = cliedFechacreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE_NUEVO.CLIEV_USUARIOMODIFICACION
     *
     * @return the value of COMEXST_CLIENTE_NUEVO.CLIEV_USUARIOMODIFICACION
     *
     * @mbg.generated
     */
    public String getClievUsuariomodificacion() {
        return clievUsuariomodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE_NUEVO.CLIEV_USUARIOMODIFICACION
     *
     * @param clievUsuariomodificacion the value for COMEXST_CLIENTE_NUEVO.CLIEV_USUARIOMODIFICACION
     *
     * @mbg.generated
     */
    public void setClievUsuariomodificacion(String clievUsuariomodificacion) {
        this.clievUsuariomodificacion = clievUsuariomodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE_NUEVO.CLIED_FECHAMODIFICACION
     *
     * @return the value of COMEXST_CLIENTE_NUEVO.CLIED_FECHAMODIFICACION
     *
     * @mbg.generated
     */
    public Date getCliedFechamodificacion() {
        return cliedFechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE_NUEVO.CLIED_FECHAMODIFICACION
     *
     * @param cliedFechamodificacion the value for COMEXST_CLIENTE_NUEVO.CLIED_FECHAMODIFICACION
     *
     * @mbg.generated
     */
    public void setCliedFechamodificacion(Date cliedFechamodificacion) {
        this.cliedFechamodificacion = cliedFechamodificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMEXST_CLIENTE_NUEVO.CLIEN_ESTADO
     *
     * @return the value of COMEXST_CLIENTE_NUEVO.CLIEN_ESTADO
     *
     * @mbg.generated
     */
    public Short getClienEstado() {
        return clienEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMEXST_CLIENTE_NUEVO.CLIEN_ESTADO
     *
     * @param clienEstado the value for COMEXST_CLIENTE_NUEVO.CLIEN_ESTADO
     *
     * @mbg.generated
     */
    public void setClienEstado(Short clienEstado) {
        this.clienEstado = clienEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clienId=").append(clienId);
        sb.append(", clievCodigosap=").append(clievCodigosap);
        sb.append(", clievNombre=").append(clievNombre);
        sb.append(", clievUsuariocreacion=").append(clievUsuariocreacion);
        sb.append(", cliedFechacreacion=").append(cliedFechacreacion);
        sb.append(", clievUsuariomodificacion=").append(clievUsuariomodificacion);
        sb.append(", cliedFechamodificacion=").append(cliedFechamodificacion);
        sb.append(", clienEstado=").append(clienEstado);
        sb.append("]");
        return sb.toString();
    }
}