package com.caasa.comexsap.exportaciones.model.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ComexstExportacionpedidoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public ComexstExportacionpedidoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEpednIdIsNull() {
            addCriterion("EPEDN_ID is null");
            return (Criteria) this;
        }

        public Criteria andEpednIdIsNotNull() {
            addCriterion("EPEDN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEpednIdEqualTo(Integer value) {
            addCriterion("EPEDN_ID =", value, "epednId");
            return (Criteria) this;
        }

        public Criteria andEpednIdNotEqualTo(Integer value) {
            addCriterion("EPEDN_ID <>", value, "epednId");
            return (Criteria) this;
        }

        public Criteria andEpednIdGreaterThan(Integer value) {
            addCriterion("EPEDN_ID >", value, "epednId");
            return (Criteria) this;
        }

        public Criteria andEpednIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_ID >=", value, "epednId");
            return (Criteria) this;
        }

        public Criteria andEpednIdLessThan(Integer value) {
            addCriterion("EPEDN_ID <", value, "epednId");
            return (Criteria) this;
        }

        public Criteria andEpednIdLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_ID <=", value, "epednId");
            return (Criteria) this;
        }

        public Criteria andEpednIdIn(List<Integer> values) {
            addCriterion("EPEDN_ID in", values, "epednId");
            return (Criteria) this;
        }

        public Criteria andEpednIdNotIn(List<Integer> values) {
            addCriterion("EPEDN_ID not in", values, "epednId");
            return (Criteria) this;
        }

        public Criteria andEpednIdBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_ID between", value1, value2, "epednId");
            return (Criteria) this;
        }

        public Criteria andEpednIdNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_ID not between", value1, value2, "epednId");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionIsNull() {
            addCriterion("EPEDN_IDEXPORTACION is null");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionIsNotNull() {
            addCriterion("EPEDN_IDEXPORTACION is not null");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionEqualTo(Integer value) {
            addCriterion("EPEDN_IDEXPORTACION =", value, "epednIdexportacion");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionNotEqualTo(Integer value) {
            addCriterion("EPEDN_IDEXPORTACION <>", value, "epednIdexportacion");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionGreaterThan(Integer value) {
            addCriterion("EPEDN_IDEXPORTACION >", value, "epednIdexportacion");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDEXPORTACION >=", value, "epednIdexportacion");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionLessThan(Integer value) {
            addCriterion("EPEDN_IDEXPORTACION <", value, "epednIdexportacion");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDEXPORTACION <=", value, "epednIdexportacion");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionIn(List<Integer> values) {
            addCriterion("EPEDN_IDEXPORTACION in", values, "epednIdexportacion");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionNotIn(List<Integer> values) {
            addCriterion("EPEDN_IDEXPORTACION not in", values, "epednIdexportacion");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDEXPORTACION between", value1, value2, "epednIdexportacion");
            return (Criteria) this;
        }

        public Criteria andEpednIdexportacionNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDEXPORTACION not between", value1, value2, "epednIdexportacion");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpIsNull() {
            addCriterion("EPEDV_PEDIDOPCP is null");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpIsNotNull() {
            addCriterion("EPEDV_PEDIDOPCP is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpEqualTo(String value) {
            addCriterion("EPEDV_PEDIDOPCP =", value, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpNotEqualTo(String value) {
            addCriterion("EPEDV_PEDIDOPCP <>", value, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpGreaterThan(String value) {
            addCriterion("EPEDV_PEDIDOPCP >", value, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_PEDIDOPCP >=", value, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpLessThan(String value) {
            addCriterion("EPEDV_PEDIDOPCP <", value, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_PEDIDOPCP <=", value, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpLike(String value) {
            addCriterion("EPEDV_PEDIDOPCP like", value, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpNotLike(String value) {
            addCriterion("EPEDV_PEDIDOPCP not like", value, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpIn(List<String> values) {
            addCriterion("EPEDV_PEDIDOPCP in", values, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpNotIn(List<String> values) {
            addCriterion("EPEDV_PEDIDOPCP not in", values, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpBetween(String value1, String value2) {
            addCriterion("EPEDV_PEDIDOPCP between", value1, value2, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidopcpNotBetween(String value1, String value2) {
            addCriterion("EPEDV_PEDIDOPCP not between", value1, value2, "epedvPedidopcp");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadIsNull() {
            addCriterion("EPEDN_CANTIDAD is null");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadIsNotNull() {
            addCriterion("EPEDN_CANTIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadEqualTo(Integer value) {
            addCriterion("EPEDN_CANTIDAD =", value, "epednCantidad");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadNotEqualTo(Integer value) {
            addCriterion("EPEDN_CANTIDAD <>", value, "epednCantidad");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadGreaterThan(Integer value) {
            addCriterion("EPEDN_CANTIDAD >", value, "epednCantidad");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_CANTIDAD >=", value, "epednCantidad");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadLessThan(Integer value) {
            addCriterion("EPEDN_CANTIDAD <", value, "epednCantidad");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_CANTIDAD <=", value, "epednCantidad");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadIn(List<Integer> values) {
            addCriterion("EPEDN_CANTIDAD in", values, "epednCantidad");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadNotIn(List<Integer> values) {
            addCriterion("EPEDN_CANTIDAD not in", values, "epednCantidad");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_CANTIDAD between", value1, value2, "epednCantidad");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_CANTIDAD not between", value1, value2, "epednCantidad");
            return (Criteria) this;
        }

        public Criteria andEpednImporteIsNull() {
            addCriterion("EPEDN_IMPORTE is null");
            return (Criteria) this;
        }

        public Criteria andEpednImporteIsNotNull() {
            addCriterion("EPEDN_IMPORTE is not null");
            return (Criteria) this;
        }

        public Criteria andEpednImporteEqualTo(BigDecimal value) {
            addCriterion("EPEDN_IMPORTE =", value, "epednImporte");
            return (Criteria) this;
        }

        public Criteria andEpednImporteNotEqualTo(BigDecimal value) {
            addCriterion("EPEDN_IMPORTE <>", value, "epednImporte");
            return (Criteria) this;
        }

        public Criteria andEpednImporteGreaterThan(BigDecimal value) {
            addCriterion("EPEDN_IMPORTE >", value, "epednImporte");
            return (Criteria) this;
        }

        public Criteria andEpednImporteGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_IMPORTE >=", value, "epednImporte");
            return (Criteria) this;
        }

        public Criteria andEpednImporteLessThan(BigDecimal value) {
            addCriterion("EPEDN_IMPORTE <", value, "epednImporte");
            return (Criteria) this;
        }

        public Criteria andEpednImporteLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_IMPORTE <=", value, "epednImporte");
            return (Criteria) this;
        }

        public Criteria andEpednImporteIn(List<BigDecimal> values) {
            addCriterion("EPEDN_IMPORTE in", values, "epednImporte");
            return (Criteria) this;
        }

        public Criteria andEpednImporteNotIn(List<BigDecimal> values) {
            addCriterion("EPEDN_IMPORTE not in", values, "epednImporte");
            return (Criteria) this;
        }

        public Criteria andEpednImporteBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_IMPORTE between", value1, value2, "epednImporte");
            return (Criteria) this;
        }

        public Criteria andEpednImporteNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_IMPORTE not between", value1, value2, "epednImporte");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapIsNull() {
            addCriterion("EPEDV_PEDIDOSAP is null");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapIsNotNull() {
            addCriterion("EPEDV_PEDIDOSAP is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapEqualTo(String value) {
            addCriterion("EPEDV_PEDIDOSAP =", value, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapNotEqualTo(String value) {
            addCriterion("EPEDV_PEDIDOSAP <>", value, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapGreaterThan(String value) {
            addCriterion("EPEDV_PEDIDOSAP >", value, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_PEDIDOSAP >=", value, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapLessThan(String value) {
            addCriterion("EPEDV_PEDIDOSAP <", value, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_PEDIDOSAP <=", value, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapLike(String value) {
            addCriterion("EPEDV_PEDIDOSAP like", value, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapNotLike(String value) {
            addCriterion("EPEDV_PEDIDOSAP not like", value, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapIn(List<String> values) {
            addCriterion("EPEDV_PEDIDOSAP in", values, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapNotIn(List<String> values) {
            addCriterion("EPEDV_PEDIDOSAP not in", values, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapBetween(String value1, String value2) {
            addCriterion("EPEDV_PEDIDOSAP between", value1, value2, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpedvPedidosapNotBetween(String value1, String value2) {
            addCriterion("EPEDV_PEDIDOSAP not between", value1, value2, "epedvPedidosap");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionIsNull() {
            addCriterion("EPEDN_IDPOSICION is null");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionIsNotNull() {
            addCriterion("EPEDN_IDPOSICION is not null");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionEqualTo(Integer value) {
            addCriterion("EPEDN_IDPOSICION =", value, "epednIdposicion");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionNotEqualTo(Integer value) {
            addCriterion("EPEDN_IDPOSICION <>", value, "epednIdposicion");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionGreaterThan(Integer value) {
            addCriterion("EPEDN_IDPOSICION >", value, "epednIdposicion");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDPOSICION >=", value, "epednIdposicion");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionLessThan(Integer value) {
            addCriterion("EPEDN_IDPOSICION <", value, "epednIdposicion");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDPOSICION <=", value, "epednIdposicion");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionIn(List<Integer> values) {
            addCriterion("EPEDN_IDPOSICION in", values, "epednIdposicion");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionNotIn(List<Integer> values) {
            addCriterion("EPEDN_IDPOSICION not in", values, "epednIdposicion");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDPOSICION between", value1, value2, "epednIdposicion");
            return (Criteria) this;
        }

        public Criteria andEpednIdposicionNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDPOSICION not between", value1, value2, "epednIdposicion");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioIsNull() {
            addCriterion("EPEDV_FOLIO is null");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioIsNotNull() {
            addCriterion("EPEDV_FOLIO is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioEqualTo(String value) {
            addCriterion("EPEDV_FOLIO =", value, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioNotEqualTo(String value) {
            addCriterion("EPEDV_FOLIO <>", value, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioGreaterThan(String value) {
            addCriterion("EPEDV_FOLIO >", value, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_FOLIO >=", value, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioLessThan(String value) {
            addCriterion("EPEDV_FOLIO <", value, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_FOLIO <=", value, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioLike(String value) {
            addCriterion("EPEDV_FOLIO like", value, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioNotLike(String value) {
            addCriterion("EPEDV_FOLIO not like", value, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioIn(List<String> values) {
            addCriterion("EPEDV_FOLIO in", values, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioNotIn(List<String> values) {
            addCriterion("EPEDV_FOLIO not in", values, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioBetween(String value1, String value2) {
            addCriterion("EPEDV_FOLIO between", value1, value2, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpedvFolioNotBetween(String value1, String value2) {
            addCriterion("EPEDV_FOLIO not between", value1, value2, "epedvFolio");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaIsNull() {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA is null");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaIsNotNull() {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA is not null");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaEqualTo(Integer value) {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA =", value, "epednIdpartidaarancelaria");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaNotEqualTo(Integer value) {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA <>", value, "epednIdpartidaarancelaria");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaGreaterThan(Integer value) {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA >", value, "epednIdpartidaarancelaria");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA >=", value, "epednIdpartidaarancelaria");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaLessThan(Integer value) {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA <", value, "epednIdpartidaarancelaria");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA <=", value, "epednIdpartidaarancelaria");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaIn(List<Integer> values) {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA in", values, "epednIdpartidaarancelaria");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaNotIn(List<Integer> values) {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA not in", values, "epednIdpartidaarancelaria");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA between", value1, value2, "epednIdpartidaarancelaria");
            return (Criteria) this;
        }

        public Criteria andEpednIdpartidaarancelariaNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDPARTIDAARANCELARIA not between", value1, value2, "epednIdpartidaarancelaria");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialIsNull() {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL is null");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialIsNotNull() {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialEqualTo(String value) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL =", value, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialNotEqualTo(String value) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL <>", value, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialGreaterThan(String value) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL >", value, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL >=", value, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialLessThan(String value) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL <", value, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL <=", value, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialLike(String value) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL like", value, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialNotLike(String value) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL not like", value, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialIn(List<String> values) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL in", values, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialNotIn(List<String> values) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL not in", values, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialBetween(String value1, String value2) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL between", value1, value2, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpedvDescripcioncomercialNotBetween(String value1, String value2) {
            addCriterion("EPEDV_DESCRIPCIONCOMERCIAL not between", value1, value2, "epedvDescripcioncomercial");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadIsNull() {
            addCriterion("EPEDD_FECHADISPONIBILIDAD is null");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadIsNotNull() {
            addCriterion("EPEDD_FECHADISPONIBILIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadEqualTo(Date value) {
            addCriterion("EPEDD_FECHADISPONIBILIDAD =", value, "epeddFechadisponibilidad");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadNotEqualTo(Date value) {
            addCriterion("EPEDD_FECHADISPONIBILIDAD <>", value, "epeddFechadisponibilidad");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadGreaterThan(Date value) {
            addCriterion("EPEDD_FECHADISPONIBILIDAD >", value, "epeddFechadisponibilidad");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadGreaterThanOrEqualTo(Date value) {
            addCriterion("EPEDD_FECHADISPONIBILIDAD >=", value, "epeddFechadisponibilidad");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadLessThan(Date value) {
            addCriterion("EPEDD_FECHADISPONIBILIDAD <", value, "epeddFechadisponibilidad");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadLessThanOrEqualTo(Date value) {
            addCriterion("EPEDD_FECHADISPONIBILIDAD <=", value, "epeddFechadisponibilidad");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadIn(List<Date> values) {
            addCriterion("EPEDD_FECHADISPONIBILIDAD in", values, "epeddFechadisponibilidad");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadNotIn(List<Date> values) {
            addCriterion("EPEDD_FECHADISPONIBILIDAD not in", values, "epeddFechadisponibilidad");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadBetween(Date value1, Date value2) {
            addCriterion("EPEDD_FECHADISPONIBILIDAD between", value1, value2, "epeddFechadisponibilidad");
            return (Criteria) this;
        }

        public Criteria andEpeddFechadisponibilidadNotBetween(Date value1, Date value2) {
            addCriterion("EPEDD_FECHADISPONIBILIDAD not between", value1, value2, "epeddFechadisponibilidad");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaIsNull() {
            addCriterion("EPEDN_IDUNIDADMEDIDA is null");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaIsNotNull() {
            addCriterion("EPEDN_IDUNIDADMEDIDA is not null");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDA =", value, "epednIdunidadmedida");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaNotEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDA <>", value, "epednIdunidadmedida");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaGreaterThan(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDA >", value, "epednIdunidadmedida");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDA >=", value, "epednIdunidadmedida");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaLessThan(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDA <", value, "epednIdunidadmedida");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDA <=", value, "epednIdunidadmedida");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaIn(List<Integer> values) {
            addCriterion("EPEDN_IDUNIDADMEDIDA in", values, "epednIdunidadmedida");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaNotIn(List<Integer> values) {
            addCriterion("EPEDN_IDUNIDADMEDIDA not in", values, "epednIdunidadmedida");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDUNIDADMEDIDA between", value1, value2, "epednIdunidadmedida");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDUNIDADMEDIDA not between", value1, value2, "epednIdunidadmedida");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaIsNull() {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA is null");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaIsNotNull() {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA is not null");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA =", value, "epednIdunidadmedidaventa");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaNotEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA <>", value, "epednIdunidadmedidaventa");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaGreaterThan(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA >", value, "epednIdunidadmedidaventa");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA >=", value, "epednIdunidadmedidaventa");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaLessThan(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA <", value, "epednIdunidadmedidaventa");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA <=", value, "epednIdunidadmedidaventa");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaIn(List<Integer> values) {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA in", values, "epednIdunidadmedidaventa");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaNotIn(List<Integer> values) {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA not in", values, "epednIdunidadmedidaventa");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA between", value1, value2, "epednIdunidadmedidaventa");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaventaNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDUNIDADMEDIDAVENTA not between", value1, value2, "epednIdunidadmedidaventa");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaIsNull() {
            addCriterion("EPEDN_CANTIDADVENTA is null");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaIsNotNull() {
            addCriterion("EPEDN_CANTIDADVENTA is not null");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaEqualTo(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADVENTA =", value, "epednCantidadventa");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaNotEqualTo(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADVENTA <>", value, "epednCantidadventa");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaGreaterThan(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADVENTA >", value, "epednCantidadventa");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADVENTA >=", value, "epednCantidadventa");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaLessThan(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADVENTA <", value, "epednCantidadventa");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADVENTA <=", value, "epednCantidadventa");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaIn(List<BigDecimal> values) {
            addCriterion("EPEDN_CANTIDADVENTA in", values, "epednCantidadventa");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaNotIn(List<BigDecimal> values) {
            addCriterion("EPEDN_CANTIDADVENTA not in", values, "epednCantidadventa");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_CANTIDADVENTA between", value1, value2, "epednCantidadventa");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadventaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_CANTIDADVENTA not between", value1, value2, "epednCantidadventa");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionIsNull() {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION is null");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionIsNotNull() {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION =", value, "epednIdunidadmedidaconversion");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionNotEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION <>", value, "epednIdunidadmedidaconversion");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionGreaterThan(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION >", value, "epednIdunidadmedidaconversion");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION >=", value, "epednIdunidadmedidaconversion");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionLessThan(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION <", value, "epednIdunidadmedidaconversion");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION <=", value, "epednIdunidadmedidaconversion");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionIn(List<Integer> values) {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION in", values, "epednIdunidadmedidaconversion");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionNotIn(List<Integer> values) {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION not in", values, "epednIdunidadmedidaconversion");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION between", value1, value2, "epednIdunidadmedidaconversion");
            return (Criteria) this;
        }

        public Criteria andEpednIdunidadmedidaconversionNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDUNIDADMEDIDACONVERSION not between", value1, value2, "epednIdunidadmedidaconversion");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionIsNull() {
            addCriterion("EPEDN_CANTIDADCONVERSION is null");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionIsNotNull() {
            addCriterion("EPEDN_CANTIDADCONVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionEqualTo(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADCONVERSION =", value, "epednCantidadconversion");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionNotEqualTo(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADCONVERSION <>", value, "epednCantidadconversion");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionGreaterThan(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADCONVERSION >", value, "epednCantidadconversion");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADCONVERSION >=", value, "epednCantidadconversion");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionLessThan(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADCONVERSION <", value, "epednCantidadconversion");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_CANTIDADCONVERSION <=", value, "epednCantidadconversion");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionIn(List<BigDecimal> values) {
            addCriterion("EPEDN_CANTIDADCONVERSION in", values, "epednCantidadconversion");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionNotIn(List<BigDecimal> values) {
            addCriterion("EPEDN_CANTIDADCONVERSION not in", values, "epednCantidadconversion");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_CANTIDADCONVERSION between", value1, value2, "epednCantidadconversion");
            return (Criteria) this;
        }

        public Criteria andEpednCantidadconversionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_CANTIDADCONVERSION not between", value1, value2, "epednCantidadconversion");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionIsNull() {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION is null");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionIsNotNull() {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION =", value, "epednPreciounitarioconversion");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionNotEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION <>", value, "epednPreciounitarioconversion");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionGreaterThan(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION >", value, "epednPreciounitarioconversion");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION >=", value, "epednPreciounitarioconversion");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionLessThan(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION <", value, "epednPreciounitarioconversion");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION <=", value, "epednPreciounitarioconversion");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionIn(List<BigDecimal> values) {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION in", values, "epednPreciounitarioconversion");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionNotIn(List<BigDecimal> values) {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION not in", values, "epednPreciounitarioconversion");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION between", value1, value2, "epednPreciounitarioconversion");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioconversionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_PRECIOUNITARIOCONVERSION not between", value1, value2, "epednPreciounitarioconversion");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapIsNull() {
            addCriterion("EPEDN_ITEMSAP is null");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapIsNotNull() {
            addCriterion("EPEDN_ITEMSAP is not null");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapEqualTo(Integer value) {
            addCriterion("EPEDN_ITEMSAP =", value, "epednItemsap");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapNotEqualTo(Integer value) {
            addCriterion("EPEDN_ITEMSAP <>", value, "epednItemsap");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapGreaterThan(Integer value) {
            addCriterion("EPEDN_ITEMSAP >", value, "epednItemsap");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_ITEMSAP >=", value, "epednItemsap");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapLessThan(Integer value) {
            addCriterion("EPEDN_ITEMSAP <", value, "epednItemsap");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_ITEMSAP <=", value, "epednItemsap");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapIn(List<Integer> values) {
            addCriterion("EPEDN_ITEMSAP in", values, "epednItemsap");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapNotIn(List<Integer> values) {
            addCriterion("EPEDN_ITEMSAP not in", values, "epednItemsap");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_ITEMSAP between", value1, value2, "epednItemsap");
            return (Criteria) this;
        }

        public Criteria andEpednItemsapNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_ITEMSAP not between", value1, value2, "epednItemsap");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenIsNull() {
            addCriterion("EPEDN_IDALMACEN is null");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenIsNotNull() {
            addCriterion("EPEDN_IDALMACEN is not null");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenEqualTo(Integer value) {
            addCriterion("EPEDN_IDALMACEN =", value, "epednIdalmacen");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenNotEqualTo(Integer value) {
            addCriterion("EPEDN_IDALMACEN <>", value, "epednIdalmacen");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenGreaterThan(Integer value) {
            addCriterion("EPEDN_IDALMACEN >", value, "epednIdalmacen");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDALMACEN >=", value, "epednIdalmacen");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenLessThan(Integer value) {
            addCriterion("EPEDN_IDALMACEN <", value, "epednIdalmacen");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDALMACEN <=", value, "epednIdalmacen");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenIn(List<Integer> values) {
            addCriterion("EPEDN_IDALMACEN in", values, "epednIdalmacen");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenNotIn(List<Integer> values) {
            addCriterion("EPEDN_IDALMACEN not in", values, "epednIdalmacen");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDALMACEN between", value1, value2, "epednIdalmacen");
            return (Criteria) this;
        }

        public Criteria andEpednIdalmacenNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDALMACEN not between", value1, value2, "epednIdalmacen");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaIsNull() {
            addCriterion("EPEDN_PESOTONELADA is null");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaIsNotNull() {
            addCriterion("EPEDN_PESOTONELADA is not null");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PESOTONELADA =", value, "epednPesotonelada");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaNotEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PESOTONELADA <>", value, "epednPesotonelada");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaGreaterThan(BigDecimal value) {
            addCriterion("EPEDN_PESOTONELADA >", value, "epednPesotonelada");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PESOTONELADA >=", value, "epednPesotonelada");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaLessThan(BigDecimal value) {
            addCriterion("EPEDN_PESOTONELADA <", value, "epednPesotonelada");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PESOTONELADA <=", value, "epednPesotonelada");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaIn(List<BigDecimal> values) {
            addCriterion("EPEDN_PESOTONELADA in", values, "epednPesotonelada");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaNotIn(List<BigDecimal> values) {
            addCriterion("EPEDN_PESOTONELADA not in", values, "epednPesotonelada");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_PESOTONELADA between", value1, value2, "epednPesotonelada");
            return (Criteria) this;
        }

        public Criteria andEpednPesotoneladaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_PESOTONELADA not between", value1, value2, "epednPesotonelada");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioIsNull() {
            addCriterion("EPEDN_PRECIOUNITARIO is null");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioIsNotNull() {
            addCriterion("EPEDN_PRECIOUNITARIO is not null");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIO =", value, "epednPreciounitario");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioNotEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIO <>", value, "epednPreciounitario");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioGreaterThan(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIO >", value, "epednPreciounitario");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIO >=", value, "epednPreciounitario");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioLessThan(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIO <", value, "epednPreciounitario");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EPEDN_PRECIOUNITARIO <=", value, "epednPreciounitario");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioIn(List<BigDecimal> values) {
            addCriterion("EPEDN_PRECIOUNITARIO in", values, "epednPreciounitario");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioNotIn(List<BigDecimal> values) {
            addCriterion("EPEDN_PRECIOUNITARIO not in", values, "epednPreciounitario");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_PRECIOUNITARIO between", value1, value2, "epednPreciounitario");
            return (Criteria) this;
        }

        public Criteria andEpednPreciounitarioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EPEDN_PRECIOUNITARIO not between", value1, value2, "epednPreciounitario");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaIsNull() {
            addCriterion("EPEDN_IDMONEDA is null");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaIsNotNull() {
            addCriterion("EPEDN_IDMONEDA is not null");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaEqualTo(Integer value) {
            addCriterion("EPEDN_IDMONEDA =", value, "epednIdmoneda");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaNotEqualTo(Integer value) {
            addCriterion("EPEDN_IDMONEDA <>", value, "epednIdmoneda");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaGreaterThan(Integer value) {
            addCriterion("EPEDN_IDMONEDA >", value, "epednIdmoneda");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaGreaterThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDMONEDA >=", value, "epednIdmoneda");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaLessThan(Integer value) {
            addCriterion("EPEDN_IDMONEDA <", value, "epednIdmoneda");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaLessThanOrEqualTo(Integer value) {
            addCriterion("EPEDN_IDMONEDA <=", value, "epednIdmoneda");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaIn(List<Integer> values) {
            addCriterion("EPEDN_IDMONEDA in", values, "epednIdmoneda");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaNotIn(List<Integer> values) {
            addCriterion("EPEDN_IDMONEDA not in", values, "epednIdmoneda");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDMONEDA between", value1, value2, "epednIdmoneda");
            return (Criteria) this;
        }

        public Criteria andEpednIdmonedaNotBetween(Integer value1, Integer value2) {
            addCriterion("EPEDN_IDMONEDA not between", value1, value2, "epednIdmoneda");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapIsNull() {
            addCriterion("EPEDV_MENSAJESAP is null");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapIsNotNull() {
            addCriterion("EPEDV_MENSAJESAP is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapEqualTo(String value) {
            addCriterion("EPEDV_MENSAJESAP =", value, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapNotEqualTo(String value) {
            addCriterion("EPEDV_MENSAJESAP <>", value, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapGreaterThan(String value) {
            addCriterion("EPEDV_MENSAJESAP >", value, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_MENSAJESAP >=", value, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapLessThan(String value) {
            addCriterion("EPEDV_MENSAJESAP <", value, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_MENSAJESAP <=", value, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapLike(String value) {
            addCriterion("EPEDV_MENSAJESAP like", value, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapNotLike(String value) {
            addCriterion("EPEDV_MENSAJESAP not like", value, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapIn(List<String> values) {
            addCriterion("EPEDV_MENSAJESAP in", values, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapNotIn(List<String> values) {
            addCriterion("EPEDV_MENSAJESAP not in", values, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapBetween(String value1, String value2) {
            addCriterion("EPEDV_MENSAJESAP between", value1, value2, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvMensajesapNotBetween(String value1, String value2) {
            addCriterion("EPEDV_MENSAJESAP not between", value1, value2, "epedvMensajesap");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaIsNull() {
            addCriterion("EPEDV_ENTREGA is null");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaIsNotNull() {
            addCriterion("EPEDV_ENTREGA is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaEqualTo(String value) {
            addCriterion("EPEDV_ENTREGA =", value, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaNotEqualTo(String value) {
            addCriterion("EPEDV_ENTREGA <>", value, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaGreaterThan(String value) {
            addCriterion("EPEDV_ENTREGA >", value, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_ENTREGA >=", value, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaLessThan(String value) {
            addCriterion("EPEDV_ENTREGA <", value, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_ENTREGA <=", value, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaLike(String value) {
            addCriterion("EPEDV_ENTREGA like", value, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaNotLike(String value) {
            addCriterion("EPEDV_ENTREGA not like", value, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaIn(List<String> values) {
            addCriterion("EPEDV_ENTREGA in", values, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaNotIn(List<String> values) {
            addCriterion("EPEDV_ENTREGA not in", values, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaBetween(String value1, String value2) {
            addCriterion("EPEDV_ENTREGA between", value1, value2, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvEntregaNotBetween(String value1, String value2) {
            addCriterion("EPEDV_ENTREGA not between", value1, value2, "epedvEntrega");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoIsNull() {
            addCriterion("EPEDV_BLOQUEO is null");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoIsNotNull() {
            addCriterion("EPEDV_BLOQUEO is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoEqualTo(String value) {
            addCriterion("EPEDV_BLOQUEO =", value, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoNotEqualTo(String value) {
            addCriterion("EPEDV_BLOQUEO <>", value, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoGreaterThan(String value) {
            addCriterion("EPEDV_BLOQUEO >", value, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_BLOQUEO >=", value, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoLessThan(String value) {
            addCriterion("EPEDV_BLOQUEO <", value, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_BLOQUEO <=", value, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoLike(String value) {
            addCriterion("EPEDV_BLOQUEO like", value, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoNotLike(String value) {
            addCriterion("EPEDV_BLOQUEO not like", value, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoIn(List<String> values) {
            addCriterion("EPEDV_BLOQUEO in", values, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoNotIn(List<String> values) {
            addCriterion("EPEDV_BLOQUEO not in", values, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoBetween(String value1, String value2) {
            addCriterion("EPEDV_BLOQUEO between", value1, value2, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvBloqueoNotBetween(String value1, String value2) {
            addCriterion("EPEDV_BLOQUEO not between", value1, value2, "epedvBloqueo");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaIsNull() {
            addCriterion("EPEDV_REFERENCIA is null");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaIsNotNull() {
            addCriterion("EPEDV_REFERENCIA is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaEqualTo(String value) {
            addCriterion("EPEDV_REFERENCIA =", value, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaNotEqualTo(String value) {
            addCriterion("EPEDV_REFERENCIA <>", value, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaGreaterThan(String value) {
            addCriterion("EPEDV_REFERENCIA >", value, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_REFERENCIA >=", value, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaLessThan(String value) {
            addCriterion("EPEDV_REFERENCIA <", value, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_REFERENCIA <=", value, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaLike(String value) {
            addCriterion("EPEDV_REFERENCIA like", value, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaNotLike(String value) {
            addCriterion("EPEDV_REFERENCIA not like", value, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaIn(List<String> values) {
            addCriterion("EPEDV_REFERENCIA in", values, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaNotIn(List<String> values) {
            addCriterion("EPEDV_REFERENCIA not in", values, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaBetween(String value1, String value2) {
            addCriterion("EPEDV_REFERENCIA between", value1, value2, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvReferenciaNotBetween(String value1, String value2) {
            addCriterion("EPEDV_REFERENCIA not between", value1, value2, "epedvReferencia");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoIsNull() {
            addCriterion("EPEDV_COMPONENTETEXTO is null");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoIsNotNull() {
            addCriterion("EPEDV_COMPONENTETEXTO is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoEqualTo(String value) {
            addCriterion("EPEDV_COMPONENTETEXTO =", value, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoNotEqualTo(String value) {
            addCriterion("EPEDV_COMPONENTETEXTO <>", value, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoGreaterThan(String value) {
            addCriterion("EPEDV_COMPONENTETEXTO >", value, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_COMPONENTETEXTO >=", value, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoLessThan(String value) {
            addCriterion("EPEDV_COMPONENTETEXTO <", value, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_COMPONENTETEXTO <=", value, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoLike(String value) {
            addCriterion("EPEDV_COMPONENTETEXTO like", value, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoNotLike(String value) {
            addCriterion("EPEDV_COMPONENTETEXTO not like", value, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoIn(List<String> values) {
            addCriterion("EPEDV_COMPONENTETEXTO in", values, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoNotIn(List<String> values) {
            addCriterion("EPEDV_COMPONENTETEXTO not in", values, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoBetween(String value1, String value2) {
            addCriterion("EPEDV_COMPONENTETEXTO between", value1, value2, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvComponentetextoNotBetween(String value1, String value2) {
            addCriterion("EPEDV_COMPONENTETEXTO not between", value1, value2, "epedvComponentetexto");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionIsNull() {
            addCriterion("EPEDV_USUARIOCREACION is null");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionIsNotNull() {
            addCriterion("EPEDV_USUARIOCREACION is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionEqualTo(String value) {
            addCriterion("EPEDV_USUARIOCREACION =", value, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionNotEqualTo(String value) {
            addCriterion("EPEDV_USUARIOCREACION <>", value, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionGreaterThan(String value) {
            addCriterion("EPEDV_USUARIOCREACION >", value, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_USUARIOCREACION >=", value, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionLessThan(String value) {
            addCriterion("EPEDV_USUARIOCREACION <", value, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_USUARIOCREACION <=", value, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionLike(String value) {
            addCriterion("EPEDV_USUARIOCREACION like", value, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionNotLike(String value) {
            addCriterion("EPEDV_USUARIOCREACION not like", value, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionIn(List<String> values) {
            addCriterion("EPEDV_USUARIOCREACION in", values, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionNotIn(List<String> values) {
            addCriterion("EPEDV_USUARIOCREACION not in", values, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionBetween(String value1, String value2) {
            addCriterion("EPEDV_USUARIOCREACION between", value1, value2, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariocreacionNotBetween(String value1, String value2) {
            addCriterion("EPEDV_USUARIOCREACION not between", value1, value2, "epedvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionIsNull() {
            addCriterion("EPEDD_FECHACREACION is null");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionIsNotNull() {
            addCriterion("EPEDD_FECHACREACION is not null");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionEqualTo(Date value) {
            addCriterion("EPEDD_FECHACREACION =", value, "epeddFechacreacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionNotEqualTo(Date value) {
            addCriterion("EPEDD_FECHACREACION <>", value, "epeddFechacreacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionGreaterThan(Date value) {
            addCriterion("EPEDD_FECHACREACION >", value, "epeddFechacreacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionGreaterThanOrEqualTo(Date value) {
            addCriterion("EPEDD_FECHACREACION >=", value, "epeddFechacreacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionLessThan(Date value) {
            addCriterion("EPEDD_FECHACREACION <", value, "epeddFechacreacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionLessThanOrEqualTo(Date value) {
            addCriterion("EPEDD_FECHACREACION <=", value, "epeddFechacreacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionIn(List<Date> values) {
            addCriterion("EPEDD_FECHACREACION in", values, "epeddFechacreacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionNotIn(List<Date> values) {
            addCriterion("EPEDD_FECHACREACION not in", values, "epeddFechacreacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionBetween(Date value1, Date value2) {
            addCriterion("EPEDD_FECHACREACION between", value1, value2, "epeddFechacreacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechacreacionNotBetween(Date value1, Date value2) {
            addCriterion("EPEDD_FECHACREACION not between", value1, value2, "epeddFechacreacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionIsNull() {
            addCriterion("EPEDV_USUARIOMODIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionIsNotNull() {
            addCriterion("EPEDV_USUARIOMODIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionEqualTo(String value) {
            addCriterion("EPEDV_USUARIOMODIFICACION =", value, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionNotEqualTo(String value) {
            addCriterion("EPEDV_USUARIOMODIFICACION <>", value, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionGreaterThan(String value) {
            addCriterion("EPEDV_USUARIOMODIFICACION >", value, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_USUARIOMODIFICACION >=", value, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionLessThan(String value) {
            addCriterion("EPEDV_USUARIOMODIFICACION <", value, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_USUARIOMODIFICACION <=", value, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionLike(String value) {
            addCriterion("EPEDV_USUARIOMODIFICACION like", value, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionNotLike(String value) {
            addCriterion("EPEDV_USUARIOMODIFICACION not like", value, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionIn(List<String> values) {
            addCriterion("EPEDV_USUARIOMODIFICACION in", values, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionNotIn(List<String> values) {
            addCriterion("EPEDV_USUARIOMODIFICACION not in", values, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionBetween(String value1, String value2) {
            addCriterion("EPEDV_USUARIOMODIFICACION between", value1, value2, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpedvUsuariomodificacionNotBetween(String value1, String value2) {
            addCriterion("EPEDV_USUARIOMODIFICACION not between", value1, value2, "epedvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionIsNull() {
            addCriterion("EPEDD_FECHAMODIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionIsNotNull() {
            addCriterion("EPEDD_FECHAMODIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionEqualTo(Date value) {
            addCriterion("EPEDD_FECHAMODIFICACION =", value, "epeddFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionNotEqualTo(Date value) {
            addCriterion("EPEDD_FECHAMODIFICACION <>", value, "epeddFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionGreaterThan(Date value) {
            addCriterion("EPEDD_FECHAMODIFICACION >", value, "epeddFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionGreaterThanOrEqualTo(Date value) {
            addCriterion("EPEDD_FECHAMODIFICACION >=", value, "epeddFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionLessThan(Date value) {
            addCriterion("EPEDD_FECHAMODIFICACION <", value, "epeddFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionLessThanOrEqualTo(Date value) {
            addCriterion("EPEDD_FECHAMODIFICACION <=", value, "epeddFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionIn(List<Date> values) {
            addCriterion("EPEDD_FECHAMODIFICACION in", values, "epeddFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionNotIn(List<Date> values) {
            addCriterion("EPEDD_FECHAMODIFICACION not in", values, "epeddFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionBetween(Date value1, Date value2) {
            addCriterion("EPEDD_FECHAMODIFICACION between", value1, value2, "epeddFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andEpeddFechamodificacionNotBetween(Date value1, Date value2) {
            addCriterion("EPEDD_FECHAMODIFICACION not between", value1, value2, "epeddFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoIsNull() {
            addCriterion("EPEDN_ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoIsNotNull() {
            addCriterion("EPEDN_ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoEqualTo(Short value) {
            addCriterion("EPEDN_ESTADO =", value, "epednEstado");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoNotEqualTo(Short value) {
            addCriterion("EPEDN_ESTADO <>", value, "epednEstado");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoGreaterThan(Short value) {
            addCriterion("EPEDN_ESTADO >", value, "epednEstado");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoGreaterThanOrEqualTo(Short value) {
            addCriterion("EPEDN_ESTADO >=", value, "epednEstado");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoLessThan(Short value) {
            addCriterion("EPEDN_ESTADO <", value, "epednEstado");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoLessThanOrEqualTo(Short value) {
            addCriterion("EPEDN_ESTADO <=", value, "epednEstado");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoIn(List<Short> values) {
            addCriterion("EPEDN_ESTADO in", values, "epednEstado");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoNotIn(List<Short> values) {
            addCriterion("EPEDN_ESTADO not in", values, "epednEstado");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoBetween(Short value1, Short value2) {
            addCriterion("EPEDN_ESTADO between", value1, value2, "epednEstado");
            return (Criteria) this;
        }

        public Criteria andEpednEstadoNotBetween(Short value1, Short value2) {
            addCriterion("EPEDN_ESTADO not between", value1, value2, "epednEstado");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapIsNull() {
            addCriterion("EPEDV_CODIGOSAP is null");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapIsNotNull() {
            addCriterion("EPEDV_CODIGOSAP is not null");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapEqualTo(String value) {
            addCriterion("EPEDV_CODIGOSAP =", value, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapNotEqualTo(String value) {
            addCriterion("EPEDV_CODIGOSAP <>", value, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapGreaterThan(String value) {
            addCriterion("EPEDV_CODIGOSAP >", value, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapGreaterThanOrEqualTo(String value) {
            addCriterion("EPEDV_CODIGOSAP >=", value, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapLessThan(String value) {
            addCriterion("EPEDV_CODIGOSAP <", value, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapLessThanOrEqualTo(String value) {
            addCriterion("EPEDV_CODIGOSAP <=", value, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapLike(String value) {
            addCriterion("EPEDV_CODIGOSAP like", value, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapNotLike(String value) {
            addCriterion("EPEDV_CODIGOSAP not like", value, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapIn(List<String> values) {
            addCriterion("EPEDV_CODIGOSAP in", values, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapNotIn(List<String> values) {
            addCriterion("EPEDV_CODIGOSAP not in", values, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapBetween(String value1, String value2) {
            addCriterion("EPEDV_CODIGOSAP between", value1, value2, "epedvCodigosap");
            return (Criteria) this;
        }

        public Criteria andEpedvCodigosapNotBetween(String value1, String value2) {
            addCriterion("EPEDV_CODIGOSAP not between", value1, value2, "epedvCodigosap");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_EXPORTACIONPEDIDO
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}