package com.caasa.comexsap.exportaciones.model.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ComexstContenedorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public ComexstContenedorExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andContnIdIsNull() {
            addCriterion("CONTN_ID is null");
            return (Criteria) this;
        }

        public Criteria andContnIdIsNotNull() {
            addCriterion("CONTN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andContnIdEqualTo(Integer value) {
            addCriterion("CONTN_ID =", value, "contnId");
            return (Criteria) this;
        }

        public Criteria andContnIdNotEqualTo(Integer value) {
            addCriterion("CONTN_ID <>", value, "contnId");
            return (Criteria) this;
        }

        public Criteria andContnIdGreaterThan(Integer value) {
            addCriterion("CONTN_ID >", value, "contnId");
            return (Criteria) this;
        }

        public Criteria andContnIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CONTN_ID >=", value, "contnId");
            return (Criteria) this;
        }

        public Criteria andContnIdLessThan(Integer value) {
            addCriterion("CONTN_ID <", value, "contnId");
            return (Criteria) this;
        }

        public Criteria andContnIdLessThanOrEqualTo(Integer value) {
            addCriterion("CONTN_ID <=", value, "contnId");
            return (Criteria) this;
        }

        public Criteria andContnIdIn(List<Integer> values) {
            addCriterion("CONTN_ID in", values, "contnId");
            return (Criteria) this;
        }

        public Criteria andContnIdNotIn(List<Integer> values) {
            addCriterion("CONTN_ID not in", values, "contnId");
            return (Criteria) this;
        }

        public Criteria andContnIdBetween(Integer value1, Integer value2) {
            addCriterion("CONTN_ID between", value1, value2, "contnId");
            return (Criteria) this;
        }

        public Criteria andContnIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CONTN_ID not between", value1, value2, "contnId");
            return (Criteria) this;
        }

        public Criteria andContnNumeroIsNull() {
            addCriterion("CONTN_NUMERO is null");
            return (Criteria) this;
        }

        public Criteria andContnNumeroIsNotNull() {
            addCriterion("CONTN_NUMERO is not null");
            return (Criteria) this;
        }

        public Criteria andContnNumeroEqualTo(Integer value) {
            addCriterion("CONTN_NUMERO =", value, "contnNumero");
            return (Criteria) this;
        }

        public Criteria andContnNumeroNotEqualTo(Integer value) {
            addCriterion("CONTN_NUMERO <>", value, "contnNumero");
            return (Criteria) this;
        }

        public Criteria andContnNumeroGreaterThan(Integer value) {
            addCriterion("CONTN_NUMERO >", value, "contnNumero");
            return (Criteria) this;
        }

        public Criteria andContnNumeroGreaterThanOrEqualTo(Integer value) {
            addCriterion("CONTN_NUMERO >=", value, "contnNumero");
            return (Criteria) this;
        }

        public Criteria andContnNumeroLessThan(Integer value) {
            addCriterion("CONTN_NUMERO <", value, "contnNumero");
            return (Criteria) this;
        }

        public Criteria andContnNumeroLessThanOrEqualTo(Integer value) {
            addCriterion("CONTN_NUMERO <=", value, "contnNumero");
            return (Criteria) this;
        }

        public Criteria andContnNumeroIn(List<Integer> values) {
            addCriterion("CONTN_NUMERO in", values, "contnNumero");
            return (Criteria) this;
        }

        public Criteria andContnNumeroNotIn(List<Integer> values) {
            addCriterion("CONTN_NUMERO not in", values, "contnNumero");
            return (Criteria) this;
        }

        public Criteria andContnNumeroBetween(Integer value1, Integer value2) {
            addCriterion("CONTN_NUMERO between", value1, value2, "contnNumero");
            return (Criteria) this;
        }

        public Criteria andContnNumeroNotBetween(Integer value1, Integer value2) {
            addCriterion("CONTN_NUMERO not between", value1, value2, "contnNumero");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionIsNull() {
            addCriterion("CONTV_DESCRIPCION is null");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionIsNotNull() {
            addCriterion("CONTV_DESCRIPCION is not null");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionEqualTo(String value) {
            addCriterion("CONTV_DESCRIPCION =", value, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionNotEqualTo(String value) {
            addCriterion("CONTV_DESCRIPCION <>", value, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionGreaterThan(String value) {
            addCriterion("CONTV_DESCRIPCION >", value, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_DESCRIPCION >=", value, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionLessThan(String value) {
            addCriterion("CONTV_DESCRIPCION <", value, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionLessThanOrEqualTo(String value) {
            addCriterion("CONTV_DESCRIPCION <=", value, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionLike(String value) {
            addCriterion("CONTV_DESCRIPCION like", value, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionNotLike(String value) {
            addCriterion("CONTV_DESCRIPCION not like", value, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionIn(List<String> values) {
            addCriterion("CONTV_DESCRIPCION in", values, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionNotIn(List<String> values) {
            addCriterion("CONTV_DESCRIPCION not in", values, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionBetween(String value1, String value2) {
            addCriterion("CONTV_DESCRIPCION between", value1, value2, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDescripcionNotBetween(String value1, String value2) {
            addCriterion("CONTV_DESCRIPCION not between", value1, value2, "contvDescripcion");
            return (Criteria) this;
        }

        public Criteria andContvDtsapIsNull() {
            addCriterion("CONTV_DTSAP is null");
            return (Criteria) this;
        }

        public Criteria andContvDtsapIsNotNull() {
            addCriterion("CONTV_DTSAP is not null");
            return (Criteria) this;
        }

        public Criteria andContvDtsapEqualTo(String value) {
            addCriterion("CONTV_DTSAP =", value, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapNotEqualTo(String value) {
            addCriterion("CONTV_DTSAP <>", value, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapGreaterThan(String value) {
            addCriterion("CONTV_DTSAP >", value, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_DTSAP >=", value, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapLessThan(String value) {
            addCriterion("CONTV_DTSAP <", value, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapLessThanOrEqualTo(String value) {
            addCriterion("CONTV_DTSAP <=", value, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapLike(String value) {
            addCriterion("CONTV_DTSAP like", value, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapNotLike(String value) {
            addCriterion("CONTV_DTSAP not like", value, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapIn(List<String> values) {
            addCriterion("CONTV_DTSAP in", values, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapNotIn(List<String> values) {
            addCriterion("CONTV_DTSAP not in", values, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapBetween(String value1, String value2) {
            addCriterion("CONTV_DTSAP between", value1, value2, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvDtsapNotBetween(String value1, String value2) {
            addCriterion("CONTV_DTSAP not between", value1, value2, "contvDtsap");
            return (Criteria) this;
        }

        public Criteria andContvChoferIsNull() {
            addCriterion("CONTV_CHOFER is null");
            return (Criteria) this;
        }

        public Criteria andContvChoferIsNotNull() {
            addCriterion("CONTV_CHOFER is not null");
            return (Criteria) this;
        }

        public Criteria andContvChoferEqualTo(String value) {
            addCriterion("CONTV_CHOFER =", value, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferNotEqualTo(String value) {
            addCriterion("CONTV_CHOFER <>", value, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferGreaterThan(String value) {
            addCriterion("CONTV_CHOFER >", value, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_CHOFER >=", value, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferLessThan(String value) {
            addCriterion("CONTV_CHOFER <", value, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferLessThanOrEqualTo(String value) {
            addCriterion("CONTV_CHOFER <=", value, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferLike(String value) {
            addCriterion("CONTV_CHOFER like", value, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferNotLike(String value) {
            addCriterion("CONTV_CHOFER not like", value, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferIn(List<String> values) {
            addCriterion("CONTV_CHOFER in", values, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferNotIn(List<String> values) {
            addCriterion("CONTV_CHOFER not in", values, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferBetween(String value1, String value2) {
            addCriterion("CONTV_CHOFER between", value1, value2, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvChoferNotBetween(String value1, String value2) {
            addCriterion("CONTV_CHOFER not between", value1, value2, "contvChofer");
            return (Criteria) this;
        }

        public Criteria andContvPlacaIsNull() {
            addCriterion("CONTV_PLACA is null");
            return (Criteria) this;
        }

        public Criteria andContvPlacaIsNotNull() {
            addCriterion("CONTV_PLACA is not null");
            return (Criteria) this;
        }

        public Criteria andContvPlacaEqualTo(String value) {
            addCriterion("CONTV_PLACA =", value, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaNotEqualTo(String value) {
            addCriterion("CONTV_PLACA <>", value, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaGreaterThan(String value) {
            addCriterion("CONTV_PLACA >", value, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_PLACA >=", value, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaLessThan(String value) {
            addCriterion("CONTV_PLACA <", value, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaLessThanOrEqualTo(String value) {
            addCriterion("CONTV_PLACA <=", value, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaLike(String value) {
            addCriterion("CONTV_PLACA like", value, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaNotLike(String value) {
            addCriterion("CONTV_PLACA not like", value, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaIn(List<String> values) {
            addCriterion("CONTV_PLACA in", values, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaNotIn(List<String> values) {
            addCriterion("CONTV_PLACA not in", values, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaBetween(String value1, String value2) {
            addCriterion("CONTV_PLACA between", value1, value2, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacaNotBetween(String value1, String value2) {
            addCriterion("CONTV_PLACA not between", value1, value2, "contvPlaca");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteIsNull() {
            addCriterion("CONTV_PLACACARRETE is null");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteIsNotNull() {
            addCriterion("CONTV_PLACACARRETE is not null");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteEqualTo(String value) {
            addCriterion("CONTV_PLACACARRETE =", value, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteNotEqualTo(String value) {
            addCriterion("CONTV_PLACACARRETE <>", value, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteGreaterThan(String value) {
            addCriterion("CONTV_PLACACARRETE >", value, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_PLACACARRETE >=", value, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteLessThan(String value) {
            addCriterion("CONTV_PLACACARRETE <", value, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteLessThanOrEqualTo(String value) {
            addCriterion("CONTV_PLACACARRETE <=", value, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteLike(String value) {
            addCriterion("CONTV_PLACACARRETE like", value, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteNotLike(String value) {
            addCriterion("CONTV_PLACACARRETE not like", value, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteIn(List<String> values) {
            addCriterion("CONTV_PLACACARRETE in", values, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteNotIn(List<String> values) {
            addCriterion("CONTV_PLACACARRETE not in", values, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteBetween(String value1, String value2) {
            addCriterion("CONTV_PLACACARRETE between", value1, value2, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvPlacacarreteNotBetween(String value1, String value2) {
            addCriterion("CONTV_PLACACARRETE not between", value1, value2, "contvPlacacarrete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteIsNull() {
            addCriterion("CONTV_BREVETE is null");
            return (Criteria) this;
        }

        public Criteria andContvBreveteIsNotNull() {
            addCriterion("CONTV_BREVETE is not null");
            return (Criteria) this;
        }

        public Criteria andContvBreveteEqualTo(String value) {
            addCriterion("CONTV_BREVETE =", value, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteNotEqualTo(String value) {
            addCriterion("CONTV_BREVETE <>", value, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteGreaterThan(String value) {
            addCriterion("CONTV_BREVETE >", value, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_BREVETE >=", value, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteLessThan(String value) {
            addCriterion("CONTV_BREVETE <", value, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteLessThanOrEqualTo(String value) {
            addCriterion("CONTV_BREVETE <=", value, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteLike(String value) {
            addCriterion("CONTV_BREVETE like", value, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteNotLike(String value) {
            addCriterion("CONTV_BREVETE not like", value, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteIn(List<String> values) {
            addCriterion("CONTV_BREVETE in", values, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteNotIn(List<String> values) {
            addCriterion("CONTV_BREVETE not in", values, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteBetween(String value1, String value2) {
            addCriterion("CONTV_BREVETE between", value1, value2, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvBreveteNotBetween(String value1, String value2) {
            addCriterion("CONTV_BREVETE not between", value1, value2, "contvBrevete");
            return (Criteria) this;
        }

        public Criteria andContvCodigoIsNull() {
            addCriterion("CONTV_CODIGO is null");
            return (Criteria) this;
        }

        public Criteria andContvCodigoIsNotNull() {
            addCriterion("CONTV_CODIGO is not null");
            return (Criteria) this;
        }

        public Criteria andContvCodigoEqualTo(String value) {
            addCriterion("CONTV_CODIGO =", value, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoNotEqualTo(String value) {
            addCriterion("CONTV_CODIGO <>", value, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoGreaterThan(String value) {
            addCriterion("CONTV_CODIGO >", value, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_CODIGO >=", value, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoLessThan(String value) {
            addCriterion("CONTV_CODIGO <", value, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoLessThanOrEqualTo(String value) {
            addCriterion("CONTV_CODIGO <=", value, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoLike(String value) {
            addCriterion("CONTV_CODIGO like", value, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoNotLike(String value) {
            addCriterion("CONTV_CODIGO not like", value, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoIn(List<String> values) {
            addCriterion("CONTV_CODIGO in", values, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoNotIn(List<String> values) {
            addCriterion("CONTV_CODIGO not in", values, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoBetween(String value1, String value2) {
            addCriterion("CONTV_CODIGO between", value1, value2, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvCodigoNotBetween(String value1, String value2) {
            addCriterion("CONTV_CODIGO not between", value1, value2, "contvCodigo");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1IsNull() {
            addCriterion("CONTV_PRECINTO1 is null");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1IsNotNull() {
            addCriterion("CONTV_PRECINTO1 is not null");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1EqualTo(String value) {
            addCriterion("CONTV_PRECINTO1 =", value, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1NotEqualTo(String value) {
            addCriterion("CONTV_PRECINTO1 <>", value, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1GreaterThan(String value) {
            addCriterion("CONTV_PRECINTO1 >", value, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1GreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_PRECINTO1 >=", value, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1LessThan(String value) {
            addCriterion("CONTV_PRECINTO1 <", value, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1LessThanOrEqualTo(String value) {
            addCriterion("CONTV_PRECINTO1 <=", value, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1Like(String value) {
            addCriterion("CONTV_PRECINTO1 like", value, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1NotLike(String value) {
            addCriterion("CONTV_PRECINTO1 not like", value, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1In(List<String> values) {
            addCriterion("CONTV_PRECINTO1 in", values, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1NotIn(List<String> values) {
            addCriterion("CONTV_PRECINTO1 not in", values, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1Between(String value1, String value2) {
            addCriterion("CONTV_PRECINTO1 between", value1, value2, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto1NotBetween(String value1, String value2) {
            addCriterion("CONTV_PRECINTO1 not between", value1, value2, "contvPrecinto1");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2IsNull() {
            addCriterion("CONTV_PRECINTO2 is null");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2IsNotNull() {
            addCriterion("CONTV_PRECINTO2 is not null");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2EqualTo(String value) {
            addCriterion("CONTV_PRECINTO2 =", value, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2NotEqualTo(String value) {
            addCriterion("CONTV_PRECINTO2 <>", value, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2GreaterThan(String value) {
            addCriterion("CONTV_PRECINTO2 >", value, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2GreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_PRECINTO2 >=", value, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2LessThan(String value) {
            addCriterion("CONTV_PRECINTO2 <", value, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2LessThanOrEqualTo(String value) {
            addCriterion("CONTV_PRECINTO2 <=", value, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2Like(String value) {
            addCriterion("CONTV_PRECINTO2 like", value, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2NotLike(String value) {
            addCriterion("CONTV_PRECINTO2 not like", value, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2In(List<String> values) {
            addCriterion("CONTV_PRECINTO2 in", values, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2NotIn(List<String> values) {
            addCriterion("CONTV_PRECINTO2 not in", values, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2Between(String value1, String value2) {
            addCriterion("CONTV_PRECINTO2 between", value1, value2, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvPrecinto2NotBetween(String value1, String value2) {
            addCriterion("CONTV_PRECINTO2 not between", value1, value2, "contvPrecinto2");
            return (Criteria) this;
        }

        public Criteria andContvBultoIsNull() {
            addCriterion("CONTV_BULTO is null");
            return (Criteria) this;
        }

        public Criteria andContvBultoIsNotNull() {
            addCriterion("CONTV_BULTO is not null");
            return (Criteria) this;
        }

        public Criteria andContvBultoEqualTo(String value) {
            addCriterion("CONTV_BULTO =", value, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoNotEqualTo(String value) {
            addCriterion("CONTV_BULTO <>", value, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoGreaterThan(String value) {
            addCriterion("CONTV_BULTO >", value, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_BULTO >=", value, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoLessThan(String value) {
            addCriterion("CONTV_BULTO <", value, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoLessThanOrEqualTo(String value) {
            addCriterion("CONTV_BULTO <=", value, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoLike(String value) {
            addCriterion("CONTV_BULTO like", value, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoNotLike(String value) {
            addCriterion("CONTV_BULTO not like", value, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoIn(List<String> values) {
            addCriterion("CONTV_BULTO in", values, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoNotIn(List<String> values) {
            addCriterion("CONTV_BULTO not in", values, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoBetween(String value1, String value2) {
            addCriterion("CONTV_BULTO between", value1, value2, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvBultoNotBetween(String value1, String value2) {
            addCriterion("CONTV_BULTO not between", value1, value2, "contvBulto");
            return (Criteria) this;
        }

        public Criteria andContvTacoIsNull() {
            addCriterion("CONTV_TACO is null");
            return (Criteria) this;
        }

        public Criteria andContvTacoIsNotNull() {
            addCriterion("CONTV_TACO is not null");
            return (Criteria) this;
        }

        public Criteria andContvTacoEqualTo(String value) {
            addCriterion("CONTV_TACO =", value, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoNotEqualTo(String value) {
            addCriterion("CONTV_TACO <>", value, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoGreaterThan(String value) {
            addCriterion("CONTV_TACO >", value, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_TACO >=", value, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoLessThan(String value) {
            addCriterion("CONTV_TACO <", value, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoLessThanOrEqualTo(String value) {
            addCriterion("CONTV_TACO <=", value, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoLike(String value) {
            addCriterion("CONTV_TACO like", value, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoNotLike(String value) {
            addCriterion("CONTV_TACO not like", value, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoIn(List<String> values) {
            addCriterion("CONTV_TACO in", values, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoNotIn(List<String> values) {
            addCriterion("CONTV_TACO not in", values, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoBetween(String value1, String value2) {
            addCriterion("CONTV_TACO between", value1, value2, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvTacoNotBetween(String value1, String value2) {
            addCriterion("CONTV_TACO not between", value1, value2, "contvTaco");
            return (Criteria) this;
        }

        public Criteria andContvBookingIsNull() {
            addCriterion("CONTV_BOOKING is null");
            return (Criteria) this;
        }

        public Criteria andContvBookingIsNotNull() {
            addCriterion("CONTV_BOOKING is not null");
            return (Criteria) this;
        }

        public Criteria andContvBookingEqualTo(String value) {
            addCriterion("CONTV_BOOKING =", value, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingNotEqualTo(String value) {
            addCriterion("CONTV_BOOKING <>", value, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingGreaterThan(String value) {
            addCriterion("CONTV_BOOKING >", value, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_BOOKING >=", value, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingLessThan(String value) {
            addCriterion("CONTV_BOOKING <", value, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingLessThanOrEqualTo(String value) {
            addCriterion("CONTV_BOOKING <=", value, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingLike(String value) {
            addCriterion("CONTV_BOOKING like", value, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingNotLike(String value) {
            addCriterion("CONTV_BOOKING not like", value, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingIn(List<String> values) {
            addCriterion("CONTV_BOOKING in", values, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingNotIn(List<String> values) {
            addCriterion("CONTV_BOOKING not in", values, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingBetween(String value1, String value2) {
            addCriterion("CONTV_BOOKING between", value1, value2, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvBookingNotBetween(String value1, String value2) {
            addCriterion("CONTV_BOOKING not between", value1, value2, "contvBooking");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioIsNull() {
            addCriterion("CONTV_HORAINICIO is null");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioIsNotNull() {
            addCriterion("CONTV_HORAINICIO is not null");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioEqualTo(String value) {
            addCriterion("CONTV_HORAINICIO =", value, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioNotEqualTo(String value) {
            addCriterion("CONTV_HORAINICIO <>", value, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioGreaterThan(String value) {
            addCriterion("CONTV_HORAINICIO >", value, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_HORAINICIO >=", value, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioLessThan(String value) {
            addCriterion("CONTV_HORAINICIO <", value, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioLessThanOrEqualTo(String value) {
            addCriterion("CONTV_HORAINICIO <=", value, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioLike(String value) {
            addCriterion("CONTV_HORAINICIO like", value, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioNotLike(String value) {
            addCriterion("CONTV_HORAINICIO not like", value, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioIn(List<String> values) {
            addCriterion("CONTV_HORAINICIO in", values, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioNotIn(List<String> values) {
            addCriterion("CONTV_HORAINICIO not in", values, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioBetween(String value1, String value2) {
            addCriterion("CONTV_HORAINICIO between", value1, value2, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorainicioNotBetween(String value1, String value2) {
            addCriterion("CONTV_HORAINICIO not between", value1, value2, "contvHorainicio");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalIsNull() {
            addCriterion("CONTV_HORAFINAL is null");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalIsNotNull() {
            addCriterion("CONTV_HORAFINAL is not null");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalEqualTo(String value) {
            addCriterion("CONTV_HORAFINAL =", value, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalNotEqualTo(String value) {
            addCriterion("CONTV_HORAFINAL <>", value, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalGreaterThan(String value) {
            addCriterion("CONTV_HORAFINAL >", value, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_HORAFINAL >=", value, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalLessThan(String value) {
            addCriterion("CONTV_HORAFINAL <", value, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalLessThanOrEqualTo(String value) {
            addCriterion("CONTV_HORAFINAL <=", value, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalLike(String value) {
            addCriterion("CONTV_HORAFINAL like", value, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalNotLike(String value) {
            addCriterion("CONTV_HORAFINAL not like", value, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalIn(List<String> values) {
            addCriterion("CONTV_HORAFINAL in", values, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalNotIn(List<String> values) {
            addCriterion("CONTV_HORAFINAL not in", values, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalBetween(String value1, String value2) {
            addCriterion("CONTV_HORAFINAL between", value1, value2, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContvHorafinalNotBetween(String value1, String value2) {
            addCriterion("CONTV_HORAFINAL not between", value1, value2, "contvHorafinal");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexIsNull() {
            addCriterion("CONTN_PESOCOMEX is null");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexIsNotNull() {
            addCriterion("CONTN_PESOCOMEX is not null");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexEqualTo(BigDecimal value) {
            addCriterion("CONTN_PESOCOMEX =", value, "contnPesocomex");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexNotEqualTo(BigDecimal value) {
            addCriterion("CONTN_PESOCOMEX <>", value, "contnPesocomex");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexGreaterThan(BigDecimal value) {
            addCriterion("CONTN_PESOCOMEX >", value, "contnPesocomex");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CONTN_PESOCOMEX >=", value, "contnPesocomex");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexLessThan(BigDecimal value) {
            addCriterion("CONTN_PESOCOMEX <", value, "contnPesocomex");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CONTN_PESOCOMEX <=", value, "contnPesocomex");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexIn(List<BigDecimal> values) {
            addCriterion("CONTN_PESOCOMEX in", values, "contnPesocomex");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexNotIn(List<BigDecimal> values) {
            addCriterion("CONTN_PESOCOMEX not in", values, "contnPesocomex");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CONTN_PESOCOMEX between", value1, value2, "contnPesocomex");
            return (Criteria) this;
        }

        public Criteria andContnPesocomexNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CONTN_PESOCOMEX not between", value1, value2, "contnPesocomex");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionIsNull() {
            addCriterion("CONTN_IDEXPORTACION is null");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionIsNotNull() {
            addCriterion("CONTN_IDEXPORTACION is not null");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionEqualTo(Integer value) {
            addCriterion("CONTN_IDEXPORTACION =", value, "contnIdexportacion");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionNotEqualTo(Integer value) {
            addCriterion("CONTN_IDEXPORTACION <>", value, "contnIdexportacion");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionGreaterThan(Integer value) {
            addCriterion("CONTN_IDEXPORTACION >", value, "contnIdexportacion");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionGreaterThanOrEqualTo(Integer value) {
            addCriterion("CONTN_IDEXPORTACION >=", value, "contnIdexportacion");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionLessThan(Integer value) {
            addCriterion("CONTN_IDEXPORTACION <", value, "contnIdexportacion");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionLessThanOrEqualTo(Integer value) {
            addCriterion("CONTN_IDEXPORTACION <=", value, "contnIdexportacion");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionIn(List<Integer> values) {
            addCriterion("CONTN_IDEXPORTACION in", values, "contnIdexportacion");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionNotIn(List<Integer> values) {
            addCriterion("CONTN_IDEXPORTACION not in", values, "contnIdexportacion");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionBetween(Integer value1, Integer value2) {
            addCriterion("CONTN_IDEXPORTACION between", value1, value2, "contnIdexportacion");
            return (Criteria) this;
        }

        public Criteria andContnIdexportacionNotBetween(Integer value1, Integer value2) {
            addCriterion("CONTN_IDEXPORTACION not between", value1, value2, "contnIdexportacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionIsNull() {
            addCriterion("CONTV_USUARIOCREACION is null");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionIsNotNull() {
            addCriterion("CONTV_USUARIOCREACION is not null");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionEqualTo(String value) {
            addCriterion("CONTV_USUARIOCREACION =", value, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionNotEqualTo(String value) {
            addCriterion("CONTV_USUARIOCREACION <>", value, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionGreaterThan(String value) {
            addCriterion("CONTV_USUARIOCREACION >", value, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_USUARIOCREACION >=", value, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionLessThan(String value) {
            addCriterion("CONTV_USUARIOCREACION <", value, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionLessThanOrEqualTo(String value) {
            addCriterion("CONTV_USUARIOCREACION <=", value, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionLike(String value) {
            addCriterion("CONTV_USUARIOCREACION like", value, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionNotLike(String value) {
            addCriterion("CONTV_USUARIOCREACION not like", value, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionIn(List<String> values) {
            addCriterion("CONTV_USUARIOCREACION in", values, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionNotIn(List<String> values) {
            addCriterion("CONTV_USUARIOCREACION not in", values, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionBetween(String value1, String value2) {
            addCriterion("CONTV_USUARIOCREACION between", value1, value2, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariocreacionNotBetween(String value1, String value2) {
            addCriterion("CONTV_USUARIOCREACION not between", value1, value2, "contvUsuariocreacion");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionIsNull() {
            addCriterion("CONTD_FECHACREACION is null");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionIsNotNull() {
            addCriterion("CONTD_FECHACREACION is not null");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionEqualTo(Date value) {
            addCriterion("CONTD_FECHACREACION =", value, "contdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionNotEqualTo(Date value) {
            addCriterion("CONTD_FECHACREACION <>", value, "contdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionGreaterThan(Date value) {
            addCriterion("CONTD_FECHACREACION >", value, "contdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionGreaterThanOrEqualTo(Date value) {
            addCriterion("CONTD_FECHACREACION >=", value, "contdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionLessThan(Date value) {
            addCriterion("CONTD_FECHACREACION <", value, "contdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionLessThanOrEqualTo(Date value) {
            addCriterion("CONTD_FECHACREACION <=", value, "contdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionIn(List<Date> values) {
            addCriterion("CONTD_FECHACREACION in", values, "contdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionNotIn(List<Date> values) {
            addCriterion("CONTD_FECHACREACION not in", values, "contdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionBetween(Date value1, Date value2) {
            addCriterion("CONTD_FECHACREACION between", value1, value2, "contdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andContdFechacreacionNotBetween(Date value1, Date value2) {
            addCriterion("CONTD_FECHACREACION not between", value1, value2, "contdFechacreacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionIsNull() {
            addCriterion("CONTV_USUARIOMODIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionIsNotNull() {
            addCriterion("CONTV_USUARIOMODIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionEqualTo(String value) {
            addCriterion("CONTV_USUARIOMODIFICACION =", value, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionNotEqualTo(String value) {
            addCriterion("CONTV_USUARIOMODIFICACION <>", value, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionGreaterThan(String value) {
            addCriterion("CONTV_USUARIOMODIFICACION >", value, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionGreaterThanOrEqualTo(String value) {
            addCriterion("CONTV_USUARIOMODIFICACION >=", value, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionLessThan(String value) {
            addCriterion("CONTV_USUARIOMODIFICACION <", value, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionLessThanOrEqualTo(String value) {
            addCriterion("CONTV_USUARIOMODIFICACION <=", value, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionLike(String value) {
            addCriterion("CONTV_USUARIOMODIFICACION like", value, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionNotLike(String value) {
            addCriterion("CONTV_USUARIOMODIFICACION not like", value, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionIn(List<String> values) {
            addCriterion("CONTV_USUARIOMODIFICACION in", values, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionNotIn(List<String> values) {
            addCriterion("CONTV_USUARIOMODIFICACION not in", values, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionBetween(String value1, String value2) {
            addCriterion("CONTV_USUARIOMODIFICACION between", value1, value2, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContvUsuariomodificacionNotBetween(String value1, String value2) {
            addCriterion("CONTV_USUARIOMODIFICACION not between", value1, value2, "contvUsuariomodificacion");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionIsNull() {
            addCriterion("CONTD_FECHAMODIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionIsNotNull() {
            addCriterion("CONTD_FECHAMODIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionEqualTo(Date value) {
            addCriterion("CONTD_FECHAMODIFICACION =", value, "contdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionNotEqualTo(Date value) {
            addCriterion("CONTD_FECHAMODIFICACION <>", value, "contdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionGreaterThan(Date value) {
            addCriterion("CONTD_FECHAMODIFICACION >", value, "contdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionGreaterThanOrEqualTo(Date value) {
            addCriterion("CONTD_FECHAMODIFICACION >=", value, "contdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionLessThan(Date value) {
            addCriterion("CONTD_FECHAMODIFICACION <", value, "contdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionLessThanOrEqualTo(Date value) {
            addCriterion("CONTD_FECHAMODIFICACION <=", value, "contdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionIn(List<Date> values) {
            addCriterion("CONTD_FECHAMODIFICACION in", values, "contdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionNotIn(List<Date> values) {
            addCriterion("CONTD_FECHAMODIFICACION not in", values, "contdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionBetween(Date value1, Date value2) {
            addCriterion("CONTD_FECHAMODIFICACION between", value1, value2, "contdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andContdFechamodificacionNotBetween(Date value1, Date value2) {
            addCriterion("CONTD_FECHAMODIFICACION not between", value1, value2, "contdFechamodificacion");
            return (Criteria) this;
        }

        public Criteria andContnEstadoIsNull() {
            addCriterion("CONTN_ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andContnEstadoIsNotNull() {
            addCriterion("CONTN_ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andContnEstadoEqualTo(Short value) {
            addCriterion("CONTN_ESTADO =", value, "contnEstado");
            return (Criteria) this;
        }

        public Criteria andContnEstadoNotEqualTo(Short value) {
            addCriterion("CONTN_ESTADO <>", value, "contnEstado");
            return (Criteria) this;
        }

        public Criteria andContnEstadoGreaterThan(Short value) {
            addCriterion("CONTN_ESTADO >", value, "contnEstado");
            return (Criteria) this;
        }

        public Criteria andContnEstadoGreaterThanOrEqualTo(Short value) {
            addCriterion("CONTN_ESTADO >=", value, "contnEstado");
            return (Criteria) this;
        }

        public Criteria andContnEstadoLessThan(Short value) {
            addCriterion("CONTN_ESTADO <", value, "contnEstado");
            return (Criteria) this;
        }

        public Criteria andContnEstadoLessThanOrEqualTo(Short value) {
            addCriterion("CONTN_ESTADO <=", value, "contnEstado");
            return (Criteria) this;
        }

        public Criteria andContnEstadoIn(List<Short> values) {
            addCriterion("CONTN_ESTADO in", values, "contnEstado");
            return (Criteria) this;
        }

        public Criteria andContnEstadoNotIn(List<Short> values) {
            addCriterion("CONTN_ESTADO not in", values, "contnEstado");
            return (Criteria) this;
        }

        public Criteria andContnEstadoBetween(Short value1, Short value2) {
            addCriterion("CONTN_ESTADO between", value1, value2, "contnEstado");
            return (Criteria) this;
        }

        public Criteria andContnEstadoNotBetween(Short value1, Short value2) {
            addCriterion("CONTN_ESTADO not between", value1, value2, "contnEstado");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}