export class PedidoFirme {
  public id: number
  public idCarpeta: number
  public idCliente: number
  public tipoSolicitud: number
  public idCondicionPago: number
  public idDespacho: number
  public idDestinatario: number
  public idEstadoDocumento: number
  public idFormaPago: number
  public idIncoterm: number
  public idIncotermComercial: number
  public idListaPrecio: number
  public idMoneda: number
  public idPaisPuertoDestino: number
  public idPaisPuertoOrigen: number
  public idPuertoDestino: number
  public idPuertoOrigen: number
  public idRuta: number
  public idPadre: number
  public idTipoSolicPadre: number
  public idLugarDespacho: number
  public idTipoTransporte: number
  public idFacturacion: number
  public idPesoObjetivo: number
  public idToleranciaProduccion: number
  public idPesoEtiqueta: number
  public idNumeroEtiqueta: number
  public importeFlete: number
  public seguroInternacional: number
  public nodeId: string
  public nombreCliente: string
  public nombreCliente2: string
  public nombreCondicionPago: string
  public nombreContacto: string
  public nombreDespacho: string
  public nombreDestinatario: string
  public nombreDestinatario2: string
  public nombreEstadoDocumento: string
  public nombreFormaPago: string
  public nombreIncoterm: string
  public nombreListaPrecio: string
  public nombreMoneda: string
  public nombreNuevoCliente: string
  public nombreNuevoDestinatario: string
  public nombrePaisPuertoDestino: string
  public nombrePaisPuertoOrigen: string
  public nombrePuertoDestino: string
  public nombrePuertoOrigen: string
  public nombreRuta: string
  public nombreTipoTransporte: string
  public nombreLugarDespacho: string
  public nombreFacturacion: string
  public nombrePesoObjetivo: string
  public nombreToleranciaProd: string
  public nombrePesoEtiqueta: string
  public nombreAlmacenaje: string
  public nombreNumeroEtiqueta: string
  public nombreIncotermComercial: string
  public numeroContenedor: number
  public observacion: string
  public tiempoEntrega: string
  public vigenciaOferta: number
  public cargoContacto: string
  public codigoPedido: string
  public codigoCliente: string
  public codigoCondicionPago: string
  public codigoDespacho: string
  public codigoDestinatario: string
  public codigoEstadoDocumento: string
  public codigoFormaPago: string
  public codigoIncoterm: string
  public codigoIncotermComercial: string
  public codigoListaPrecio: string
  public codigoMoneda: string
  public codigoPuertoDestino: string
  public codigoPuertoOrigen: string
  public codigoRuta: string
  public codigoTipoTransporte: string
  public codigoFacturacion: string
  public codigoPesoEtiqueta: string
  public codigoPesoObjetivo: string
  public codigoToleranciaProduccion: string
  public codigoAlmacenaje: string
  public codigoNumeroEtiqueta: string
  public codigoLugarDespacho: string
  public correoContacto: string
  public fechaListaPrecio: string
  public fechaSolicitud: string
  public fechaDespachoRequerido: string
  public clienteSapExiste: boolean
  public cargoContactoAdicional: string
  public nombreContactoAdicional: string
  public correoContactoAdicional: string
  public anticipo: number
  public condicionDescarga: string
  public idAlmacenaje: number
  public gastosOperativos: string
  public deal: string
  public incotermTotal: string
  public lote: string
  public customerName: string
  public destinationPort: string
}
