package com.caasa.comexsap.exportaciones.enums;

public enum TablasAplicativoEnum {

	CONFIGT_DOMINIO("CONFIGT_DOMINIO"),
	CONFIGT_PARAMETRO("CONFIGT_PARAMETRO"),
	COMEXST_PEDIDO("COMEXST_PEDIDO"),
	COMEXST_PEDIDOPOSICION("COMEXST_PEDIDOPOSICION"),
	COMEXST_CLIENTE_NUEVO("COMEXST_CLIENTE_NUEVO"),
	COMEXST_CLIENTE("COMEXST_CLIENTE"),
	COMEXST_DESTINATARIO_NUEVO("COMEXST_DESTINATARIO_NUEVO"),
	COMEXST_PRODUCTO("COMEXST_PRODUCTO"),
	COMEXST_UNIDADMEDIDA("COMEXST_UNIDADMEDIDA"),
	COMEXST_DESTINATARIO("COMEXST_DESTINATARIO"),
	COMEXST_CARPETA("COMEXST_CARPETA"),
	COMEXST_CARPETADOCUMENTO("COMEXST_CARPETADOCUMENTO"),
	COMEXST_EXPORTACION("COMEXST_EXPORTACION"),
	COMEXST_EXPORTACION_PEDIDO("COMEXST_EXPORTACIONPEDIDO"),
	COMEXST_EXPORTACION_PEDIDO_POSICION("COMEXST_PEDIDOEXPORTACIONPOSICION"),
	COMEXST_EXPORTACION_FACTURA("COMEXST_EXPORTACIONFACTURA"),
	COMEXST_FACTURA("COMEXST_FACTURA"),
	COMEXST_DOCUMENTOAGENTEADUANA("COMEXST_DOCUMENTOAGENTEADUANA"),
	COMEXST_SERVICIO("COMEXST_SERVICIO"),
	COMEXST_GRUPOCORREODETALLE("COMEXST_GRUPOCORREODETALLE"),
	COMEXST_CONTENEDOR("COMEXST_CONTENEDOR"),
	COMEXST_PACKINGLIST("COMEXST_PACKINGLIST"),
	COMEXST_PACKINGLIST_CARGASUELTA("COMEXST_PACKINGLIST_CARGASUELTA"),
	COMEXST_ETIQUETA("COMEXST_ETIQUETA"),
	COMEXST_EXPORTACION_ETIQUETA("COMEXST_EXPORTACION_ETIQUETA"),
	COMEXST_PACKINGLIST_AEREO("COMEXST_PACKINGLIST_AEREO"),
	COMEXST_CONTROL_GASTOS("COMEXST_CONTROL_GASTOS"),
	COMEXST_CONTROL_GASTOS_DETALLE("COMEXST_CONTROL_GASTOS_DETALLE");

	private String value;

	private TablasAplicativoEnum(String value) {
		setValue(value);
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	

}
