export class Cotizacion {
  public idCotizacion: number
  public idCarpeta: number
  public idCliente: number
  public tipoSolicitud: number
  public idCondicionPago: number
  public idDespacho: number
  public idDestinatario: number
  public idEstadoDocumento: number
  public idFormaPago: number
  public idIncoterm: number
  public idIncotermComercial: number
  public idListaPrecio: number
  public idMoneda: number
  public idPaisPuertoDestino: number
  public idPaisPuertoOrigen: number
  public idPuertoDestino: number
  public idPuertoOrigen: number
  public idRuta: number
  public idPadre: number
  public idGuardado: number
  public idTipoTransporte: number
  public importeFlete: number
  public seguroInternacional: number
  public nodeId: string
  public nombreCliente: string
  public nombreCliente2: string
  public nombreCondicionPago: string
  public nombreContacto: string
  public nombreDespacho: string
  public nombreDestinatario: string
  public nombreDestinatario2: string
  public nombreEstadoDocumento: string
  public nombreFormaPago: string
  public nombreIncoterm: string
  public nombreListaPrecio: string
  public nombreMoneda: string
  public nombreNuevoCliente: string
  public nombreNuevoDestinatario: string
  public nombrePaisPuertoDestino: string
  public nombrePaisPuertoOrigen: string
  public nombrePuertoDestino: string
  public nombrePuertoOrigen: string
  public nombreRuta: string
  public nombreTipoTransporte: string
  public numeroContenedor: number
  public observacion: string
  public tiempoEntrega: string
  public vigenciaOferta: number
  public cargoContacto: string
  public codigoPedido: string
  public codigoCliente: string
  public codigoCondicionPago: string
  public codigoDespacho: string
  public codigoDestinatario: string
  public codigoEstadoDocumento: string
  public codigoFormaPago: string
  public codigoIncoterm: string
  public codigoListaPrecio: string
  public codigoMoneda: string
  public codigoPuertoDestino: string
  public codigoPuertoOrigen: string
  public codigoRuta: string
  public codigoSapPaisPuertoDest: string
  public codigoSapPaisPuestoOrig: string
  public codigoTipoTransporte: string
  public correoContacto: string
  public fechaListaPrecio: string
  public fechaSolicitud: string
  public clienteSapExiste: boolean
  public cargoContactoAdicional: string
  public nombreContactoAdicional: string
  public correoContactoAdicional: string

}
