package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstPackingcontenedor;
import com.caasa.comexsap.exportaciones.model.domain.ComexstPackingcontenedorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstPackingcontenedorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGCONTENEDOR
     *
     * @mbg.generated
     */
    long countByExample(ComexstPackingcontenedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGCONTENEDOR
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pconnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGCONTENEDOR
     *
     * @mbg.generated
     */
    int insert(ComexstPackingcontenedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGCONTENEDOR
     *
     * @mbg.generated
     */
    int insertSelective(ComexstPackingcontenedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGCONTENEDOR
     *
     * @mbg.generated
     */
    List<ComexstPackingcontenedor> selectByExample(ComexstPackingcontenedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGCONTENEDOR
     *
     * @mbg.generated
     */
    ComexstPackingcontenedor selectByPrimaryKey(Integer pconnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGCONTENEDOR
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstPackingcontenedor record, @Param("example") ComexstPackingcontenedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGCONTENEDOR
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstPackingcontenedor record, @Param("example") ComexstPackingcontenedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGCONTENEDOR
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstPackingcontenedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGCONTENEDOR
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstPackingcontenedor record);
}