package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstServicio;
import com.caasa.comexsap.exportaciones.model.domain.ComexstServicioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstServicioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIO
     *
     * @mbg.generated
     */
    long countByExample(ComexstServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer servnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIO
     *
     * @mbg.generated
     */
    int insert(ComexstServicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIO
     *
     * @mbg.generated
     */
    int insertSelective(ComexstServicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIO
     *
     * @mbg.generated
     */
    List<ComexstServicio> selectByExample(ComexstServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIO
     *
     * @mbg.generated
     */
    ComexstServicio selectByPrimaryKey(Integer servnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstServicio record, @Param("example") ComexstServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstServicio record, @Param("example") ComexstServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstServicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstServicio record);
}