package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstDocumentoagenteaduana;
import com.caasa.comexsap.exportaciones.model.domain.ComexstDocumentoagenteaduanaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstDocumentoagenteaduanaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DOCUMENTOAGENTEADUANA
     *
     * @mbg.generated
     */
    long countByExample(ComexstDocumentoagenteaduanaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DOCUMENTOAGENTEADUANA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daadnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DOCUMENTOAGENTEADUANA
     *
     * @mbg.generated
     */
    int insert(ComexstDocumentoagenteaduana record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DOCUMENTOAGENTEADUANA
     *
     * @mbg.generated
     */
    int insertSelective(ComexstDocumentoagenteaduana record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DOCUMENTOAGENTEADUANA
     *
     * @mbg.generated
     */
    List<ComexstDocumentoagenteaduana> selectByExample(ComexstDocumentoagenteaduanaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DOCUMENTOAGENTEADUANA
     *
     * @mbg.generated
     */
    ComexstDocumentoagenteaduana selectByPrimaryKey(Integer daadnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DOCUMENTOAGENTEADUANA
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstDocumentoagenteaduana record, @Param("example") ComexstDocumentoagenteaduanaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DOCUMENTOAGENTEADUANA
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstDocumentoagenteaduana record, @Param("example") ComexstDocumentoagenteaduanaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DOCUMENTOAGENTEADUANA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstDocumentoagenteaduana record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DOCUMENTOAGENTEADUANA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstDocumentoagenteaduana record);
}