package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstFacturalog;
import com.caasa.comexsap.exportaciones.model.domain.ComexstFacturalogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstFacturalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURALOG
     *
     * @mbg.generated
     */
    long countByExample(ComexstFacturalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURALOG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer flognId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURALOG
     *
     * @mbg.generated
     */
    int insert(ComexstFacturalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURALOG
     *
     * @mbg.generated
     */
    int insertSelective(ComexstFacturalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURALOG
     *
     * @mbg.generated
     */
    List<ComexstFacturalog> selectByExample(ComexstFacturalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURALOG
     *
     * @mbg.generated
     */
    ComexstFacturalog selectByPrimaryKey(Integer flognId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURALOG
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstFacturalog record, @Param("example") ComexstFacturalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURALOG
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstFacturalog record, @Param("example") ComexstFacturalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURALOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstFacturalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURALOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstFacturalog record);
}