package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstOrdenInterna;
import com.caasa.comexsap.exportaciones.model.domain.ComexstOrdenInternaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstOrdenInternaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ORDEN_INTERNA
     *
     * @mbg.generated
     */
    long countByExample(ComexstOrdenInternaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ORDEN_INTERNA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ointnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ORDEN_INTERNA
     *
     * @mbg.generated
     */
    int insert(ComexstOrdenInterna record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ORDEN_INTERNA
     *
     * @mbg.generated
     */
    int insertSelective(ComexstOrdenInterna record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ORDEN_INTERNA
     *
     * @mbg.generated
     */
    List<ComexstOrdenInterna> selectByExample(ComexstOrdenInternaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ORDEN_INTERNA
     *
     * @mbg.generated
     */
    ComexstOrdenInterna selectByPrimaryKey(Integer ointnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ORDEN_INTERNA
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstOrdenInterna record, @Param("example") ComexstOrdenInternaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ORDEN_INTERNA
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstOrdenInterna record, @Param("example") ComexstOrdenInternaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ORDEN_INTERNA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstOrdenInterna record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ORDEN_INTERNA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstOrdenInterna record);
}