package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstProducto;
import com.caasa.comexsap.exportaciones.model.domain.ComexstProductoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstProductoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PRODUCTO
     *
     * @mbg.generated
     */
    long countByExample(ComexstProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PRODUCTO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer prodnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PRODUCTO
     *
     * @mbg.generated
     */
    int insert(ComexstProducto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PRODUCTO
     *
     * @mbg.generated
     */
    int insertSelective(ComexstProducto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PRODUCTO
     *
     * @mbg.generated
     */
    List<ComexstProducto> selectByExample(ComexstProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PRODUCTO
     *
     * @mbg.generated
     */
    ComexstProducto selectByPrimaryKey(Integer prodnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PRODUCTO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstProducto record, @Param("example") ComexstProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PRODUCTO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstProducto record, @Param("example") ComexstProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PRODUCTO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstProducto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PRODUCTO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstProducto record);
}