package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstExportacionfactura;
import com.caasa.comexsap.exportaciones.model.domain.ComexstExportacionfacturaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstExportacionfacturaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONFACTURA
     *
     * @mbg.generated
     */
    long countByExample(ComexstExportacionfacturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONFACTURA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer efacnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONFACTURA
     *
     * @mbg.generated
     */
    int insert(ComexstExportacionfactura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONFACTURA
     *
     * @mbg.generated
     */
    int insertSelective(ComexstExportacionfactura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONFACTURA
     *
     * @mbg.generated
     */
    List<ComexstExportacionfactura> selectByExample(ComexstExportacionfacturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONFACTURA
     *
     * @mbg.generated
     */
    ComexstExportacionfactura selectByPrimaryKey(Integer efacnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONFACTURA
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstExportacionfactura record, @Param("example") ComexstExportacionfacturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONFACTURA
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstExportacionfactura record, @Param("example") ComexstExportacionfacturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONFACTURA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstExportacionfactura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACIONFACTURA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstExportacionfactura record);
}