package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstFactura;
import com.caasa.comexsap.exportaciones.model.domain.ComexstFacturaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstFacturaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    long countByExample(ComexstFacturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer factnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    int insert(ComexstFactura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    int insertSelective(ComexstFactura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    List<ComexstFactura> selectByExample(ComexstFacturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    ComexstFactura selectByPrimaryKey(Integer factnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstFactura record, @Param("example") ComexstFacturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstFactura record, @Param("example") ComexstFacturaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstFactura record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FACTURA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstFactura record);
}