package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstServiciodetalle;
import com.caasa.comexsap.exportaciones.model.domain.ComexstServiciodetalleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstServiciodetalleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIODETALLE
     *
     * @mbg.generated
     */
    long countByExample(ComexstServiciodetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIODETALLE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sdetnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIODETALLE
     *
     * @mbg.generated
     */
    int insert(ComexstServiciodetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIODETALLE
     *
     * @mbg.generated
     */
    int insertSelective(ComexstServiciodetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIODETALLE
     *
     * @mbg.generated
     */
    List<ComexstServiciodetalle> selectByExample(ComexstServiciodetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIODETALLE
     *
     * @mbg.generated
     */
    ComexstServiciodetalle selectByPrimaryKey(Integer sdetnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIODETALLE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstServiciodetalle record, @Param("example") ComexstServiciodetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIODETALLE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstServiciodetalle record, @Param("example") ComexstServiciodetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIODETALLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstServiciodetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_SERVICIODETALLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstServiciodetalle record);
}