package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstPedidoexportacionposicion;
import com.caasa.comexsap.exportaciones.model.domain.ComexstPedidoexportacionposicionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstPedidoexportacionposicionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOEXPORTACIONPOSICION
     *
     * @mbg.generated
     */
    long countByExample(ComexstPedidoexportacionposicionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOEXPORTACIONPOSICION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer peponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOEXPORTACIONPOSICION
     *
     * @mbg.generated
     */
    int insert(ComexstPedidoexportacionposicion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOEXPORTACIONPOSICION
     *
     * @mbg.generated
     */
    int insertSelective(ComexstPedidoexportacionposicion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOEXPORTACIONPOSICION
     *
     * @mbg.generated
     */
    List<ComexstPedidoexportacionposicion> selectByExample(ComexstPedidoexportacionposicionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOEXPORTACIONPOSICION
     *
     * @mbg.generated
     */
    ComexstPedidoexportacionposicion selectByPrimaryKey(Integer peponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOEXPORTACIONPOSICION
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstPedidoexportacionposicion record, @Param("example") ComexstPedidoexportacionposicionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOEXPORTACIONPOSICION
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstPedidoexportacionposicion record, @Param("example") ComexstPedidoexportacionposicionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOEXPORTACIONPOSICION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstPedidoexportacionposicion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOEXPORTACIONPOSICION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstPedidoexportacionposicion record);
}