package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstClienteIntercompany;
import com.caasa.comexsap.exportaciones.model.domain.ComexstClienteIntercompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstClienteIntercompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_INTERCOMPANY
     *
     * @mbg.generated
     */
    long countByExample(ComexstClienteIntercompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_INTERCOMPANY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cintnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_INTERCOMPANY
     *
     * @mbg.generated
     */
    int insert(ComexstClienteIntercompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_INTERCOMPANY
     *
     * @mbg.generated
     */
    int insertSelective(ComexstClienteIntercompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_INTERCOMPANY
     *
     * @mbg.generated
     */
    List<ComexstClienteIntercompany> selectByExample(ComexstClienteIntercompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_INTERCOMPANY
     *
     * @mbg.generated
     */
    ComexstClienteIntercompany selectByPrimaryKey(Integer cintnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_INTERCOMPANY
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstClienteIntercompany record, @Param("example") ComexstClienteIntercompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_INTERCOMPANY
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstClienteIntercompany record, @Param("example") ComexstClienteIntercompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_INTERCOMPANY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstClienteIntercompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_INTERCOMPANY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstClienteIntercompany record);
}