package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstDestinatario;
import com.caasa.comexsap.exportaciones.model.domain.ComexstDestinatarioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstDestinatarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DESTINATARIO
     *
     * @mbg.generated
     */
    long countByExample(ComexstDestinatarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DESTINATARIO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer destnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DESTINATARIO
     *
     * @mbg.generated
     */
    int insert(ComexstDestinatario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DESTINATARIO
     *
     * @mbg.generated
     */
    int insertSelective(ComexstDestinatario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DESTINATARIO
     *
     * @mbg.generated
     */
    List<ComexstDestinatario> selectByExample(ComexstDestinatarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DESTINATARIO
     *
     * @mbg.generated
     */
    ComexstDestinatario selectByPrimaryKey(Integer destnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DESTINATARIO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstDestinatario record, @Param("example") ComexstDestinatarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DESTINATARIO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstDestinatario record, @Param("example") ComexstDestinatarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DESTINATARIO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstDestinatario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_DESTINATARIO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstDestinatario record);
}