package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstCampo;
import com.caasa.comexsap.exportaciones.model.domain.ComexstCampoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstCampoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CAMPO
     *
     * @mbg.generated
     */
    long countByExample(ComexstCampoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CAMPO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer campnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CAMPO
     *
     * @mbg.generated
     */
    int insert(ComexstCampo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CAMPO
     *
     * @mbg.generated
     */
    int insertSelective(ComexstCampo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CAMPO
     *
     * @mbg.generated
     */
    List<ComexstCampo> selectByExample(ComexstCampoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CAMPO
     *
     * @mbg.generated
     */
    ComexstCampo selectByPrimaryKey(Integer campnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CAMPO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstCampo record, @Param("example") ComexstCampoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CAMPO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstCampo record, @Param("example") ComexstCampoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CAMPO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstCampo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CAMPO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstCampo record);
}