package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstControlGastosDetalle;
import com.caasa.comexsap.exportaciones.model.domain.ComexstControlGastosDetalleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstControlGastosDetalleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTROL_GASTOS_DETALLE
     *
     * @mbg.generated
     */
    long countByExample(ComexstControlGastosDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTROL_GASTOS_DETALLE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cgdenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTROL_GASTOS_DETALLE
     *
     * @mbg.generated
     */
    int insert(ComexstControlGastosDetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTROL_GASTOS_DETALLE
     *
     * @mbg.generated
     */
    int insertSelective(ComexstControlGastosDetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTROL_GASTOS_DETALLE
     *
     * @mbg.generated
     */
    List<ComexstControlGastosDetalle> selectByExample(ComexstControlGastosDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTROL_GASTOS_DETALLE
     *
     * @mbg.generated
     */
    ComexstControlGastosDetalle selectByPrimaryKey(Integer cgdenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTROL_GASTOS_DETALLE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstControlGastosDetalle record, @Param("example") ComexstControlGastosDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTROL_GASTOS_DETALLE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstControlGastosDetalle record, @Param("example") ComexstControlGastosDetalleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTROL_GASTOS_DETALLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstControlGastosDetalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTROL_GASTOS_DETALLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstControlGastosDetalle record);
}