package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstExportacion;
import com.caasa.comexsap.exportaciones.model.domain.ComexstExportacionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstExportacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACION
     *
     * @mbg.generated
     */
    long countByExample(ComexstExportacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer exponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACION
     *
     * @mbg.generated
     */
    int insert(ComexstExportacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACION
     *
     * @mbg.generated
     */
    int insertSelective(ComexstExportacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACION
     *
     * @mbg.generated
     */
    List<ComexstExportacion> selectByExample(ComexstExportacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACION
     *
     * @mbg.generated
     */
    ComexstExportacion selectByPrimaryKey(Integer exponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACION
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstExportacion record, @Param("example") ComexstExportacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACION
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstExportacion record, @Param("example") ComexstExportacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstExportacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_EXPORTACION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstExportacion record);
}