package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstTipocambio;
import com.caasa.comexsap.exportaciones.model.domain.ComexstTipocambioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstTipocambioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_TIPOCAMBIO
     *
     * @mbg.generated
     */
    long countByExample(ComexstTipocambioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_TIPOCAMBIO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tcamnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_TIPOCAMBIO
     *
     * @mbg.generated
     */
    int insert(ComexstTipocambio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_TIPOCAMBIO
     *
     * @mbg.generated
     */
    int insertSelective(ComexstTipocambio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_TIPOCAMBIO
     *
     * @mbg.generated
     */
    List<ComexstTipocambio> selectByExample(ComexstTipocambioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_TIPOCAMBIO
     *
     * @mbg.generated
     */
    ComexstTipocambio selectByPrimaryKey(Integer tcamnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_TIPOCAMBIO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstTipocambio record, @Param("example") ComexstTipocambioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_TIPOCAMBIO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstTipocambio record, @Param("example") ComexstTipocambioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_TIPOCAMBIO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstTipocambio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_TIPOCAMBIO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstTipocambio record);
}