package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstClienteNuevo;
import com.caasa.comexsap.exportaciones.model.domain.ComexstClienteNuevoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstClienteNuevoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    long countByExample(ComexstClienteNuevoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer clienId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    int insert(ComexstClienteNuevo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    int insertSelective(ComexstClienteNuevo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    List<ComexstClienteNuevo> selectByExample(ComexstClienteNuevoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    ComexstClienteNuevo selectByPrimaryKey(Integer clienId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstClienteNuevo record, @Param("example") ComexstClienteNuevoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstClienteNuevo record, @Param("example") ComexstClienteNuevoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstClienteNuevo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CLIENTE_NUEVO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstClienteNuevo record);
}