package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstAlmacen;
import com.caasa.comexsap.exportaciones.model.domain.ComexstAlmacenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstAlmacenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ALMACEN
     *
     * @mbg.generated
     */
    long countByExample(ComexstAlmacenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ALMACEN
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer almanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ALMACEN
     *
     * @mbg.generated
     */
    int insert(ComexstAlmacen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ALMACEN
     *
     * @mbg.generated
     */
    int insertSelective(ComexstAlmacen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ALMACEN
     *
     * @mbg.generated
     */
    List<ComexstAlmacen> selectByExample(ComexstAlmacenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ALMACEN
     *
     * @mbg.generated
     */
    ComexstAlmacen selectByPrimaryKey(Integer almanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ALMACEN
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstAlmacen record, @Param("example") ComexstAlmacenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ALMACEN
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstAlmacen record, @Param("example") ComexstAlmacenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ALMACEN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstAlmacen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ALMACEN
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstAlmacen record);
}