package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstPackinglist;
import com.caasa.comexsap.exportaciones.model.domain.ComexstPackinglistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstPackinglistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST
     *
     * @mbg.generated
     */
    long countByExample(ComexstPackinglistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer plisnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST
     *
     * @mbg.generated
     */
    int insert(ComexstPackinglist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST
     *
     * @mbg.generated
     */
    int insertSelective(ComexstPackinglist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST
     *
     * @mbg.generated
     */
    List<ComexstPackinglist> selectByExample(ComexstPackinglistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST
     *
     * @mbg.generated
     */
    ComexstPackinglist selectByPrimaryKey(Integer plisnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstPackinglist record, @Param("example") ComexstPackinglistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstPackinglist record, @Param("example") ComexstPackinglistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstPackinglist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstPackinglist record);
}