package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstCarpeta;
import com.caasa.comexsap.exportaciones.model.domain.ComexstCarpetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstCarpetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CARPETA
     *
     * @mbg.generated
     */
    long countByExample(ComexstCarpetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CARPETA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carpnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CARPETA
     *
     * @mbg.generated
     */
    int insert(ComexstCarpeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CARPETA
     *
     * @mbg.generated
     */
    int insertSelective(ComexstCarpeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CARPETA
     *
     * @mbg.generated
     */
    List<ComexstCarpeta> selectByExample(ComexstCarpetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CARPETA
     *
     * @mbg.generated
     */
    ComexstCarpeta selectByPrimaryKey(Integer carpnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CARPETA
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstCarpeta record, @Param("example") ComexstCarpetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CARPETA
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstCarpeta record, @Param("example") ComexstCarpetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CARPETA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstCarpeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CARPETA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstCarpeta record);
}