package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstPedidoposicion;
import com.caasa.comexsap.exportaciones.model.domain.ComexstPedidoposicionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstPedidoposicionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOPOSICION
     *
     * @mbg.generated
     */
    long countByExample(ComexstPedidoposicionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOPOSICION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pposnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOPOSICION
     *
     * @mbg.generated
     */
    int insert(ComexstPedidoposicion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOPOSICION
     *
     * @mbg.generated
     */
    int insertSelective(ComexstPedidoposicion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOPOSICION
     *
     * @mbg.generated
     */
    List<ComexstPedidoposicion> selectByExample(ComexstPedidoposicionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOPOSICION
     *
     * @mbg.generated
     */
    ComexstPedidoposicion selectByPrimaryKey(Integer pposnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOPOSICION
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstPedidoposicion record, @Param("example") ComexstPedidoposicionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOPOSICION
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstPedidoposicion record, @Param("example") ComexstPedidoposicionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOPOSICION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstPedidoposicion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDOPOSICION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstPedidoposicion record);
}