package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstCentro;
import com.caasa.comexsap.exportaciones.model.domain.ComexstCentroExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstCentroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CENTRO
     *
     * @mbg.generated
     */
    long countByExample(ComexstCentroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CENTRO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer centnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CENTRO
     *
     * @mbg.generated
     */
    int insert(ComexstCentro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CENTRO
     *
     * @mbg.generated
     */
    int insertSelective(ComexstCentro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CENTRO
     *
     * @mbg.generated
     */
    List<ComexstCentro> selectByExample(ComexstCentroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CENTRO
     *
     * @mbg.generated
     */
    ComexstCentro selectByPrimaryKey(Integer centnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CENTRO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstCentro record, @Param("example") ComexstCentroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CENTRO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstCentro record, @Param("example") ComexstCentroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CENTRO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstCentro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CENTRO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstCentro record);
}