package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstPedido;
import com.caasa.comexsap.exportaciones.model.domain.ComexstPedidoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstPedidoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDO
     *
     * @mbg.generated
     */
    long countByExample(ComexstPedidoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pedinId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDO
     *
     * @mbg.generated
     */
    int insert(ComexstPedido record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDO
     *
     * @mbg.generated
     */
    int insertSelective(ComexstPedido record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDO
     *
     * @mbg.generated
     */
    List<ComexstPedido> selectByExample(ComexstPedidoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDO
     *
     * @mbg.generated
     */
    ComexstPedido selectByPrimaryKey(Integer pedinId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstPedido record, @Param("example") ComexstPedidoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstPedido record, @Param("example") ComexstPedidoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstPedido record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PEDIDO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstPedido record);
}