package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstPackinglistAereo;
import com.caasa.comexsap.exportaciones.model.domain.ComexstPackinglistAereoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstPackinglistAereoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    long countByExample(ComexstPackinglistAereoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer plaenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    int insert(ComexstPackinglistAereo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    int insertSelective(ComexstPackinglistAereo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    List<ComexstPackinglistAereo> selectByExample(ComexstPackinglistAereoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    ComexstPackinglistAereo selectByPrimaryKey(Integer plaenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstPackinglistAereo record, @Param("example") ComexstPackinglistAereoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstPackinglistAereo record, @Param("example") ComexstPackinglistAereoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstPackinglistAereo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_PACKINGLIST_AEREO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstPackinglistAereo record);
}