package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstContenedor;
import com.caasa.comexsap.exportaciones.model.domain.ComexstContenedorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstContenedorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    long countByExample(ComexstContenedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer contnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    int insert(ComexstContenedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    int insertSelective(ComexstContenedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    List<ComexstContenedor> selectByExample(ComexstContenedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    ComexstContenedor selectByPrimaryKey(Integer contnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstContenedor record, @Param("example") ComexstContenedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstContenedor record, @Param("example") ComexstContenedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstContenedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_CONTENEDOR
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstContenedor record);
}