package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstFamiliaconversion;
import com.caasa.comexsap.exportaciones.model.domain.ComexstFamiliaconversionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstFamiliaconversionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FAMILIACONVERSION
     *
     * @mbg.generated
     */
    long countByExample(ComexstFamiliaconversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FAMILIACONVERSION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fconnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FAMILIACONVERSION
     *
     * @mbg.generated
     */
    int insert(ComexstFamiliaconversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FAMILIACONVERSION
     *
     * @mbg.generated
     */
    int insertSelective(ComexstFamiliaconversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FAMILIACONVERSION
     *
     * @mbg.generated
     */
    List<ComexstFamiliaconversion> selectByExample(ComexstFamiliaconversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FAMILIACONVERSION
     *
     * @mbg.generated
     */
    ComexstFamiliaconversion selectByPrimaryKey(Integer fconnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FAMILIACONVERSION
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstFamiliaconversion record, @Param("example") ComexstFamiliaconversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FAMILIACONVERSION
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstFamiliaconversion record, @Param("example") ComexstFamiliaconversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FAMILIACONVERSION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstFamiliaconversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_FAMILIACONVERSION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstFamiliaconversion record);
}