package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstUnidadmedida;
import com.caasa.comexsap.exportaciones.model.domain.ComexstUnidadmedidaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstUnidadmedidaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_UNIDADMEDIDA
     *
     * @mbg.generated
     */
    long countByExample(ComexstUnidadmedidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_UNIDADMEDIDA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer umednId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_UNIDADMEDIDA
     *
     * @mbg.generated
     */
    int insert(ComexstUnidadmedida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_UNIDADMEDIDA
     *
     * @mbg.generated
     */
    int insertSelective(ComexstUnidadmedida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_UNIDADMEDIDA
     *
     * @mbg.generated
     */
    List<ComexstUnidadmedida> selectByExample(ComexstUnidadmedidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_UNIDADMEDIDA
     *
     * @mbg.generated
     */
    ComexstUnidadmedida selectByPrimaryKey(Integer umednId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_UNIDADMEDIDA
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstUnidadmedida record, @Param("example") ComexstUnidadmedidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_UNIDADMEDIDA
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstUnidadmedida record, @Param("example") ComexstUnidadmedidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_UNIDADMEDIDA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstUnidadmedida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_UNIDADMEDIDA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstUnidadmedida record);
}