package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ComexstEtiqueta;
import com.caasa.comexsap.exportaciones.model.domain.ComexstEtiquetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComexstEtiquetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    long countByExample(ComexstEtiquetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer etiqnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    int insert(ComexstEtiqueta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    int insertSelective(ComexstEtiqueta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    List<ComexstEtiqueta> selectByExample(ComexstEtiquetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    ComexstEtiqueta selectByPrimaryKey(Integer etiqnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ComexstEtiqueta record, @Param("example") ComexstEtiquetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ComexstEtiqueta record, @Param("example") ComexstEtiquetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComexstEtiqueta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMEXST_ETIQUETA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComexstEtiqueta record);
}