package com.caasa.comexsap.exportaciones.model.persistence;

import com.caasa.comexsap.exportaciones.model.domain.ConfigtTablaSecuencia;
import com.caasa.comexsap.exportaciones.model.domain.ConfigtTablaSecuenciaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigtTablaSecuenciaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIGT_TABLA_SECUENCIA
     *
     * @mbg.generated
     */
    long countByExample(ConfigtTablaSecuenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIGT_TABLA_SECUENCIA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("appcode") String appcode, @Param("tabla") String tabla, @Param("secuencia") String secuencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIGT_TABLA_SECUENCIA
     *
     * @mbg.generated
     */
    int insert(ConfigtTablaSecuencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIGT_TABLA_SECUENCIA
     *
     * @mbg.generated
     */
    int insertSelective(ConfigtTablaSecuencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIGT_TABLA_SECUENCIA
     *
     * @mbg.generated
     */
    List<ConfigtTablaSecuencia> selectByExample(ConfigtTablaSecuenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIGT_TABLA_SECUENCIA
     *
     * @mbg.generated
     */
    ConfigtTablaSecuencia selectByPrimaryKey(@Param("appcode") String appcode, @Param("tabla") String tabla, @Param("secuencia") String secuencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIGT_TABLA_SECUENCIA
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConfigtTablaSecuencia record, @Param("example") ConfigtTablaSecuenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIGT_TABLA_SECUENCIA
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConfigtTablaSecuencia record, @Param("example") ConfigtTablaSecuenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIGT_TABLA_SECUENCIA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigtTablaSecuencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONFIGT_TABLA_SECUENCIA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfigtTablaSecuencia record);
}